/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.controllers;

import com.example.ApiHelper;
import com.example.Server;
import com.example.exceptions.ApiException;
import com.example.http.request.HttpMethod;
import com.example.models.Blast;
import com.example.models.Blastrequest;
import com.fasterxml.jackson.core.JsonProcessingException;
import io.apimatic.core.ApiCall;
import io.apimatic.core.GlobalConfiguration;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class CallController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public CallController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * SUPPORTED **LANGUAGE** : \* id-ID \* en-US **GENDER** : \* MALE \* FEMALE.
     * @param  body  Required parameter: Example:
     * @return    Returns the Blast response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public Blast blast(
            final Blastrequest body) throws ApiException, IOException {
        return prepareBlastRequest(body).execute();
    }

    /**
     * SUPPORTED **LANGUAGE** : \* id-ID \* en-US **GENDER** : \* MALE \* FEMALE.
     * @param  body  Required parameter: Example:
     * @return    Returns the Blast response from the API call
     */
    public CompletableFuture<Blast> blastAsync(
            final Blastrequest body) {
        try { 
            return prepareBlastRequest(body).executeAsync(); 
        } catch (Exception e) {  
            throw new CompletionException(e); 
        }
    }

    /**
     * Builds the ApiCall object for blast.
     */
    private ApiCall<Blast, ApiException> prepareBlastRequest(
            final Blastrequest body) throws JsonProcessingException, IOException {
        return new ApiCall.Builder<Blast, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/call/blast")
                        .bodyParam(param -> param.value(body))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .authenticationKey(BaseController.AUTHENTICATION_KEY)
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, Blast.class))
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}