/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for AgentLoginRequest type.
 */
public class AgentLoginRequest {
    private String actionType;
    private String agentCode;
    private String extension;
    private String agentPassword;

    /**
     * Default constructor.
     */
    public AgentLoginRequest() {
    }

    /**
     * Initialization constructor.
     * @param  actionType  String value for actionType.
     * @param  agentCode  String value for agentCode.
     * @param  extension  String value for extension.
     * @param  agentPassword  String value for agentPassword.
     */
    public AgentLoginRequest(
            String actionType,
            String agentCode,
            String extension,
            String agentPassword) {
        this.actionType = actionType;
        this.agentCode = agentCode;
        this.extension = extension;
        this.agentPassword = agentPassword;
    }

    /**
     * Getter for ActionType.
     * @return Returns the String
     */
    @JsonGetter("action_type")
    public String getActionType() {
        return actionType;
    }

    /**
     * Setter for ActionType.
     * @param actionType Value for String
     */
    @JsonSetter("action_type")
    public void setActionType(String actionType) {
        this.actionType = actionType;
    }

    /**
     * Getter for AgentCode.
     * @return Returns the String
     */
    @JsonGetter("agent_code")
    public String getAgentCode() {
        return agentCode;
    }

    /**
     * Setter for AgentCode.
     * @param agentCode Value for String
     */
    @JsonSetter("agent_code")
    public void setAgentCode(String agentCode) {
        this.agentCode = agentCode;
    }

    /**
     * Getter for Extension.
     * @return Returns the String
     */
    @JsonGetter("extension")
    public String getExtension() {
        return extension;
    }

    /**
     * Setter for Extension.
     * @param extension Value for String
     */
    @JsonSetter("extension")
    public void setExtension(String extension) {
        this.extension = extension;
    }

    /**
     * Getter for AgentPassword.
     * @return Returns the String
     */
    @JsonGetter("agent_password")
    public String getAgentPassword() {
        return agentPassword;
    }

    /**
     * Setter for AgentPassword.
     * @param agentPassword Value for String
     */
    @JsonSetter("agent_password")
    public void setAgentPassword(String agentPassword) {
        this.agentPassword = agentPassword;
    }

    /**
     * Converts this AgentLoginRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AgentLoginRequest [" + "actionType=" + actionType + ", agentCode=" + agentCode
                + ", extension=" + extension + ", agentPassword=" + agentPassword + "]";
    }

    /**
     * Builds a new {@link AgentLoginRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AgentLoginRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(actionType, agentCode, extension, agentPassword);
        return builder;
    }

    /**
     * Class to build instances of {@link AgentLoginRequest}.
     */
    public static class Builder {
        private String actionType;
        private String agentCode;
        private String extension;
        private String agentPassword;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  actionType  String value for actionType.
         * @param  agentCode  String value for agentCode.
         * @param  extension  String value for extension.
         * @param  agentPassword  String value for agentPassword.
         */
        public Builder(String actionType, String agentCode, String extension,
                String agentPassword) {
            this.actionType = actionType;
            this.agentCode = agentCode;
            this.extension = extension;
            this.agentPassword = agentPassword;
        }

        /**
         * Setter for actionType.
         * @param  actionType  String value for actionType.
         * @return Builder
         */
        public Builder actionType(String actionType) {
            this.actionType = actionType;
            return this;
        }

        /**
         * Setter for agentCode.
         * @param  agentCode  String value for agentCode.
         * @return Builder
         */
        public Builder agentCode(String agentCode) {
            this.agentCode = agentCode;
            return this;
        }

        /**
         * Setter for extension.
         * @param  extension  String value for extension.
         * @return Builder
         */
        public Builder extension(String extension) {
            this.extension = extension;
            return this;
        }

        /**
         * Setter for agentPassword.
         * @param  agentPassword  String value for agentPassword.
         * @return Builder
         */
        public Builder agentPassword(String agentPassword) {
            this.agentPassword = agentPassword;
            return this;
        }

        /**
         * Builds a new {@link AgentLoginRequest} object using the set fields.
         * @return {@link AgentLoginRequest}
         */
        public AgentLoginRequest build() {
            return new AgentLoginRequest(actionType, agentCode, extension, agentPassword);
        }
    }
}
