/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for Data1 type.
 */
public class Data1 {
    private String extension;
    private String host;
    private String deviceType;
    private String deviceOwner;
    private String secret;
    private int isOnline;
    private String deviceState;

    /**
     * Default constructor.
     */
    public Data1() {
    }

    /**
     * Initialization constructor.
     * @param  extension  String value for extension.
     * @param  host  String value for host.
     * @param  deviceType  String value for deviceType.
     * @param  deviceOwner  String value for deviceOwner.
     * @param  secret  String value for secret.
     * @param  isOnline  int value for isOnline.
     * @param  deviceState  String value for deviceState.
     */
    public Data1(
            String extension,
            String host,
            String deviceType,
            String deviceOwner,
            String secret,
            int isOnline,
            String deviceState) {
        this.extension = extension;
        this.host = host;
        this.deviceType = deviceType;
        this.deviceOwner = deviceOwner;
        this.secret = secret;
        this.isOnline = isOnline;
        this.deviceState = deviceState;
    }

    /**
     * Getter for Extension.
     * @return Returns the String
     */
    @JsonGetter("extension")
    public String getExtension() {
        return extension;
    }

    /**
     * Setter for Extension.
     * @param extension Value for String
     */
    @JsonSetter("extension")
    public void setExtension(String extension) {
        this.extension = extension;
    }

    /**
     * Getter for Host.
     * @return Returns the String
     */
    @JsonGetter("host")
    public String getHost() {
        return host;
    }

    /**
     * Setter for Host.
     * @param host Value for String
     */
    @JsonSetter("host")
    public void setHost(String host) {
        this.host = host;
    }

    /**
     * Getter for DeviceType.
     * @return Returns the String
     */
    @JsonGetter("device_type")
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * Setter for DeviceType.
     * @param deviceType Value for String
     */
    @JsonSetter("device_type")
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * Getter for DeviceOwner.
     * @return Returns the String
     */
    @JsonGetter("device_owner")
    public String getDeviceOwner() {
        return deviceOwner;
    }

    /**
     * Setter for DeviceOwner.
     * @param deviceOwner Value for String
     */
    @JsonSetter("device_owner")
    public void setDeviceOwner(String deviceOwner) {
        this.deviceOwner = deviceOwner;
    }

    /**
     * Getter for Secret.
     * @return Returns the String
     */
    @JsonGetter("secret")
    public String getSecret() {
        return secret;
    }

    /**
     * Setter for Secret.
     * @param secret Value for String
     */
    @JsonSetter("secret")
    public void setSecret(String secret) {
        this.secret = secret;
    }

    /**
     * Getter for IsOnline.
     * @return Returns the int
     */
    @JsonGetter("isOnline")
    public int getIsOnline() {
        return isOnline;
    }

    /**
     * Setter for IsOnline.
     * @param isOnline Value for int
     */
    @JsonSetter("isOnline")
    public void setIsOnline(int isOnline) {
        this.isOnline = isOnline;
    }

    /**
     * Getter for DeviceState.
     * @return Returns the String
     */
    @JsonGetter("device_state")
    public String getDeviceState() {
        return deviceState;
    }

    /**
     * Setter for DeviceState.
     * @param deviceState Value for String
     */
    @JsonSetter("device_state")
    public void setDeviceState(String deviceState) {
        this.deviceState = deviceState;
    }

    /**
     * Converts this Data1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Data1 [" + "extension=" + extension + ", host=" + host + ", deviceType="
                + deviceType + ", deviceOwner=" + deviceOwner + ", secret=" + secret + ", isOnline="
                + isOnline + ", deviceState=" + deviceState + "]";
    }

    /**
     * Builds a new {@link Data1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Data1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(extension, host, deviceType, deviceOwner, secret, isOnline,
                deviceState);
        return builder;
    }

    /**
     * Class to build instances of {@link Data1}.
     */
    public static class Builder {
        private String extension;
        private String host;
        private String deviceType;
        private String deviceOwner;
        private String secret;
        private int isOnline;
        private String deviceState;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  extension  String value for extension.
         * @param  host  String value for host.
         * @param  deviceType  String value for deviceType.
         * @param  deviceOwner  String value for deviceOwner.
         * @param  secret  String value for secret.
         * @param  isOnline  int value for isOnline.
         * @param  deviceState  String value for deviceState.
         */
        public Builder(String extension, String host, String deviceType, String deviceOwner,
                String secret, int isOnline, String deviceState) {
            this.extension = extension;
            this.host = host;
            this.deviceType = deviceType;
            this.deviceOwner = deviceOwner;
            this.secret = secret;
            this.isOnline = isOnline;
            this.deviceState = deviceState;
        }

        /**
         * Setter for extension.
         * @param  extension  String value for extension.
         * @return Builder
         */
        public Builder extension(String extension) {
            this.extension = extension;
            return this;
        }

        /**
         * Setter for host.
         * @param  host  String value for host.
         * @return Builder
         */
        public Builder host(String host) {
            this.host = host;
            return this;
        }

        /**
         * Setter for deviceType.
         * @param  deviceType  String value for deviceType.
         * @return Builder
         */
        public Builder deviceType(String deviceType) {
            this.deviceType = deviceType;
            return this;
        }

        /**
         * Setter for deviceOwner.
         * @param  deviceOwner  String value for deviceOwner.
         * @return Builder
         */
        public Builder deviceOwner(String deviceOwner) {
            this.deviceOwner = deviceOwner;
            return this;
        }

        /**
         * Setter for secret.
         * @param  secret  String value for secret.
         * @return Builder
         */
        public Builder secret(String secret) {
            this.secret = secret;
            return this;
        }

        /**
         * Setter for isOnline.
         * @param  isOnline  int value for isOnline.
         * @return Builder
         */
        public Builder isOnline(int isOnline) {
            this.isOnline = isOnline;
            return this;
        }

        /**
         * Setter for deviceState.
         * @param  deviceState  String value for deviceState.
         * @return Builder
         */
        public Builder deviceState(String deviceState) {
            this.deviceState = deviceState;
            return this;
        }

        /**
         * Builds a new {@link Data1} object using the set fields.
         * @return {@link Data1}
         */
        public Data1 build() {
            return new Data1(extension, host, deviceType, deviceOwner, secret, isOnline,
                    deviceState);
        }
    }
}
