/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for Data8 type.
 */
public class Data8 {
    private int id;
    private String aiName;
    private String displayName;
    private String trainingPhrases;
    private String messageTexts;
    private String createDate;

    /**
     * Default constructor.
     */
    public Data8() {
    }

    /**
     * Initialization constructor.
     * @param  id  int value for id.
     * @param  aiName  String value for aiName.
     * @param  displayName  String value for displayName.
     * @param  trainingPhrases  String value for trainingPhrases.
     * @param  messageTexts  String value for messageTexts.
     * @param  createDate  String value for createDate.
     */
    public Data8(
            int id,
            String aiName,
            String displayName,
            String trainingPhrases,
            String messageTexts,
            String createDate) {
        this.id = id;
        this.aiName = aiName;
        this.displayName = displayName;
        this.trainingPhrases = trainingPhrases;
        this.messageTexts = messageTexts;
        this.createDate = createDate;
    }

    /**
     * Getter for Id.
     * @return Returns the int
     */
    @JsonGetter("id")
    public int getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for int
     */
    @JsonSetter("id")
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Getter for AiName.
     * @return Returns the String
     */
    @JsonGetter("ai_name")
    public String getAiName() {
        return aiName;
    }

    /**
     * Setter for AiName.
     * @param aiName Value for String
     */
    @JsonSetter("ai_name")
    public void setAiName(String aiName) {
        this.aiName = aiName;
    }

    /**
     * Getter for DisplayName.
     * @return Returns the String
     */
    @JsonGetter("display_name")
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Setter for DisplayName.
     * @param displayName Value for String
     */
    @JsonSetter("display_name")
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /**
     * Getter for TrainingPhrases.
     * @return Returns the String
     */
    @JsonGetter("training_phrases")
    public String getTrainingPhrases() {
        return trainingPhrases;
    }

    /**
     * Setter for TrainingPhrases.
     * @param trainingPhrases Value for String
     */
    @JsonSetter("training_phrases")
    public void setTrainingPhrases(String trainingPhrases) {
        this.trainingPhrases = trainingPhrases;
    }

    /**
     * Getter for MessageTexts.
     * @return Returns the String
     */
    @JsonGetter("message_texts")
    public String getMessageTexts() {
        return messageTexts;
    }

    /**
     * Setter for MessageTexts.
     * @param messageTexts Value for String
     */
    @JsonSetter("message_texts")
    public void setMessageTexts(String messageTexts) {
        this.messageTexts = messageTexts;
    }

    /**
     * Getter for CreateDate.
     * @return Returns the String
     */
    @JsonGetter("create_date")
    public String getCreateDate() {
        return createDate;
    }

    /**
     * Setter for CreateDate.
     * @param createDate Value for String
     */
    @JsonSetter("create_date")
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * Converts this Data8 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Data8 [" + "id=" + id + ", aiName=" + aiName + ", displayName=" + displayName
                + ", trainingPhrases=" + trainingPhrases + ", messageTexts=" + messageTexts
                + ", createDate=" + createDate + "]";
    }

    /**
     * Builds a new {@link Data8.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Data8.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, aiName, displayName, trainingPhrases, messageTexts,
                createDate);
        return builder;
    }

    /**
     * Class to build instances of {@link Data8}.
     */
    public static class Builder {
        private int id;
        private String aiName;
        private String displayName;
        private String trainingPhrases;
        private String messageTexts;
        private String createDate;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  int value for id.
         * @param  aiName  String value for aiName.
         * @param  displayName  String value for displayName.
         * @param  trainingPhrases  String value for trainingPhrases.
         * @param  messageTexts  String value for messageTexts.
         * @param  createDate  String value for createDate.
         */
        public Builder(int id, String aiName, String displayName, String trainingPhrases,
                String messageTexts, String createDate) {
            this.id = id;
            this.aiName = aiName;
            this.displayName = displayName;
            this.trainingPhrases = trainingPhrases;
            this.messageTexts = messageTexts;
            this.createDate = createDate;
        }

        /**
         * Setter for id.
         * @param  id  int value for id.
         * @return Builder
         */
        public Builder id(int id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for aiName.
         * @param  aiName  String value for aiName.
         * @return Builder
         */
        public Builder aiName(String aiName) {
            this.aiName = aiName;
            return this;
        }

        /**
         * Setter for displayName.
         * @param  displayName  String value for displayName.
         * @return Builder
         */
        public Builder displayName(String displayName) {
            this.displayName = displayName;
            return this;
        }

        /**
         * Setter for trainingPhrases.
         * @param  trainingPhrases  String value for trainingPhrases.
         * @return Builder
         */
        public Builder trainingPhrases(String trainingPhrases) {
            this.trainingPhrases = trainingPhrases;
            return this;
        }

        /**
         * Setter for messageTexts.
         * @param  messageTexts  String value for messageTexts.
         * @return Builder
         */
        public Builder messageTexts(String messageTexts) {
            this.messageTexts = messageTexts;
            return this;
        }

        /**
         * Setter for createDate.
         * @param  createDate  String value for createDate.
         * @return Builder
         */
        public Builder createDate(String createDate) {
            this.createDate = createDate;
            return this;
        }

        /**
         * Builds a new {@link Data8} object using the set fields.
         * @return {@link Data8}
         */
        public Data8 build() {
            return new Data8(id, aiName, displayName, trainingPhrases, messageTexts, createDate);
        }
    }
}
