/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.example.models.containers.Data10IsActive;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for Data10 type.
 */
public class Data10 {
    private String customerCode;
    private int id;
    private int active;
    private String did;
    private String didType;
    private int activationCost;
    private String incoming;
    private String destinationDetail;
    private Data10IsActive isActive;

    /**
     * Default constructor.
     */
    public Data10() {
    }

    /**
     * Initialization constructor.
     * @param  customerCode  String value for customerCode.
     * @param  id  int value for id.
     * @param  active  int value for active.
     * @param  did  String value for did.
     * @param  didType  String value for didType.
     * @param  activationCost  int value for activationCost.
     * @param  incoming  String value for incoming.
     * @param  destinationDetail  String value for destinationDetail.
     * @param  isActive  Data10IsActive value for isActive.
     */
    public Data10(
            String customerCode,
            int id,
            int active,
            String did,
            String didType,
            int activationCost,
            String incoming,
            String destinationDetail,
            Data10IsActive isActive) {
        this.customerCode = customerCode;
        this.id = id;
        this.active = active;
        this.did = did;
        this.didType = didType;
        this.activationCost = activationCost;
        this.incoming = incoming;
        this.destinationDetail = destinationDetail;
        this.isActive = isActive;
    }

    /**
     * Getter for CustomerCode.
     * @return Returns the String
     */
    @JsonGetter("customer_code")
    public String getCustomerCode() {
        return customerCode;
    }

    /**
     * Setter for CustomerCode.
     * @param customerCode Value for String
     */
    @JsonSetter("customer_code")
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }

    /**
     * Getter for Id.
     * @return Returns the int
     */
    @JsonGetter("id")
    public int getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for int
     */
    @JsonSetter("id")
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Getter for Active.
     * @return Returns the int
     */
    @JsonGetter("active")
    public int getActive() {
        return active;
    }

    /**
     * Setter for Active.
     * @param active Value for int
     */
    @JsonSetter("active")
    public void setActive(int active) {
        this.active = active;
    }

    /**
     * Getter for Did.
     * @return Returns the String
     */
    @JsonGetter("did")
    public String getDid() {
        return did;
    }

    /**
     * Setter for Did.
     * @param did Value for String
     */
    @JsonSetter("did")
    public void setDid(String did) {
        this.did = did;
    }

    /**
     * Getter for DidType.
     * @return Returns the String
     */
    @JsonGetter("did_type")
    public String getDidType() {
        return didType;
    }

    /**
     * Setter for DidType.
     * @param didType Value for String
     */
    @JsonSetter("did_type")
    public void setDidType(String didType) {
        this.didType = didType;
    }

    /**
     * Getter for ActivationCost.
     * @return Returns the int
     */
    @JsonGetter("activation_cost")
    public int getActivationCost() {
        return activationCost;
    }

    /**
     * Setter for ActivationCost.
     * @param activationCost Value for int
     */
    @JsonSetter("activation_cost")
    public void setActivationCost(int activationCost) {
        this.activationCost = activationCost;
    }

    /**
     * Getter for Incoming.
     * @return Returns the String
     */
    @JsonGetter("incoming")
    public String getIncoming() {
        return incoming;
    }

    /**
     * Setter for Incoming.
     * @param incoming Value for String
     */
    @JsonSetter("incoming")
    public void setIncoming(String incoming) {
        this.incoming = incoming;
    }

    /**
     * Getter for DestinationDetail.
     * @return Returns the String
     */
    @JsonGetter("destination_detail")
    public String getDestinationDetail() {
        return destinationDetail;
    }

    /**
     * Setter for DestinationDetail.
     * @param destinationDetail Value for String
     */
    @JsonSetter("destination_detail")
    public void setDestinationDetail(String destinationDetail) {
        this.destinationDetail = destinationDetail;
    }

    /**
     * Getter for IsActive.
     * @return Returns the Data10IsActive
     */
    @JsonGetter("isActive")
    public Data10IsActive getIsActive() {
        return isActive;
    }

    /**
     * Setter for IsActive.
     * @param isActive Value for Data10IsActive
     */
    @JsonSetter("isActive")
    public void setIsActive(Data10IsActive isActive) {
        this.isActive = isActive;
    }

    /**
     * Converts this Data10 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Data10 [" + "customerCode=" + customerCode + ", id=" + id + ", active=" + active
                + ", did=" + did + ", didType=" + didType + ", activationCost=" + activationCost
                + ", incoming=" + incoming + ", destinationDetail=" + destinationDetail
                + ", isActive=" + isActive + "]";
    }

    /**
     * Builds a new {@link Data10.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Data10.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(customerCode, id, active, did, didType, activationCost,
                incoming, destinationDetail, isActive);
        return builder;
    }

    /**
     * Class to build instances of {@link Data10}.
     */
    public static class Builder {
        private String customerCode;
        private int id;
        private int active;
        private String did;
        private String didType;
        private int activationCost;
        private String incoming;
        private String destinationDetail;
        private Data10IsActive isActive;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  customerCode  String value for customerCode.
         * @param  id  int value for id.
         * @param  active  int value for active.
         * @param  did  String value for did.
         * @param  didType  String value for didType.
         * @param  activationCost  int value for activationCost.
         * @param  incoming  String value for incoming.
         * @param  destinationDetail  String value for destinationDetail.
         * @param  isActive  Data10IsActive value for isActive.
         */
        public Builder(String customerCode, int id, int active, String did, String didType,
                int activationCost, String incoming, String destinationDetail,
                Data10IsActive isActive) {
            this.customerCode = customerCode;
            this.id = id;
            this.active = active;
            this.did = did;
            this.didType = didType;
            this.activationCost = activationCost;
            this.incoming = incoming;
            this.destinationDetail = destinationDetail;
            this.isActive = isActive;
        }

        /**
         * Setter for customerCode.
         * @param  customerCode  String value for customerCode.
         * @return Builder
         */
        public Builder customerCode(String customerCode) {
            this.customerCode = customerCode;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  int value for id.
         * @return Builder
         */
        public Builder id(int id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for active.
         * @param  active  int value for active.
         * @return Builder
         */
        public Builder active(int active) {
            this.active = active;
            return this;
        }

        /**
         * Setter for did.
         * @param  did  String value for did.
         * @return Builder
         */
        public Builder did(String did) {
            this.did = did;
            return this;
        }

        /**
         * Setter for didType.
         * @param  didType  String value for didType.
         * @return Builder
         */
        public Builder didType(String didType) {
            this.didType = didType;
            return this;
        }

        /**
         * Setter for activationCost.
         * @param  activationCost  int value for activationCost.
         * @return Builder
         */
        public Builder activationCost(int activationCost) {
            this.activationCost = activationCost;
            return this;
        }

        /**
         * Setter for incoming.
         * @param  incoming  String value for incoming.
         * @return Builder
         */
        public Builder incoming(String incoming) {
            this.incoming = incoming;
            return this;
        }

        /**
         * Setter for destinationDetail.
         * @param  destinationDetail  String value for destinationDetail.
         * @return Builder
         */
        public Builder destinationDetail(String destinationDetail) {
            this.destinationDetail = destinationDetail;
            return this;
        }

        /**
         * Setter for isActive.
         * @param  isActive  Data10IsActive value for isActive.
         * @return Builder
         */
        public Builder isActive(Data10IsActive isActive) {
            this.isActive = isActive;
            return this;
        }

        /**
         * Builds a new {@link Data10} object using the set fields.
         * @return {@link Data10}
         */
        public Data10 build() {
            return new Data10(customerCode, id, active, did, didType, activationCost, incoming,
                    destinationDetail, isActive);
        }
    }
}
