/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for Data7 type.
 */
public class Data7 {
    private String code;
    private String name;
    private String language;
    private String gender;

    /**
     * Default constructor.
     */
    public Data7() {
    }

    /**
     * Initialization constructor.
     * @param  code  String value for code.
     * @param  name  String value for name.
     * @param  language  String value for language.
     * @param  gender  String value for gender.
     */
    public Data7(
            String code,
            String name,
            String language,
            String gender) {
        this.code = code;
        this.name = name;
        this.language = language;
        this.gender = gender;
    }

    /**
     * Getter for Code.
     * @return Returns the String
     */
    @JsonGetter("code")
    public String getCode() {
        return code;
    }

    /**
     * Setter for Code.
     * @param code Value for String
     */
    @JsonSetter("code")
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Language.
     * @return Returns the String
     */
    @JsonGetter("language")
    public String getLanguage() {
        return language;
    }

    /**
     * Setter for Language.
     * @param language Value for String
     */
    @JsonSetter("language")
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * Getter for Gender.
     * @return Returns the String
     */
    @JsonGetter("gender")
    public String getGender() {
        return gender;
    }

    /**
     * Setter for Gender.
     * @param gender Value for String
     */
    @JsonSetter("gender")
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * Converts this Data7 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Data7 [" + "code=" + code + ", name=" + name + ", language=" + language
                + ", gender=" + gender + "]";
    }

    /**
     * Builds a new {@link Data7.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Data7.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(code, name, language, gender);
        return builder;
    }

    /**
     * Class to build instances of {@link Data7}.
     */
    public static class Builder {
        private String code;
        private String name;
        private String language;
        private String gender;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  code  String value for code.
         * @param  name  String value for name.
         * @param  language  String value for language.
         * @param  gender  String value for gender.
         */
        public Builder(String code, String name, String language, String gender) {
            this.code = code;
            this.name = name;
            this.language = language;
            this.gender = gender;
        }

        /**
         * Setter for code.
         * @param  code  String value for code.
         * @return Builder
         */
        public Builder code(String code) {
            this.code = code;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for language.
         * @param  language  String value for language.
         * @return Builder
         */
        public Builder language(String language) {
            this.language = language;
            return this;
        }

        /**
         * Setter for gender.
         * @param  gender  String value for gender.
         * @return Builder
         */
        public Builder gender(String gender) {
            this.gender = gender;
            return this;
        }

        /**
         * Builds a new {@link Data7} object using the set fields.
         * @return {@link Data7}
         */
        public Data7 build() {
            return new Data7(code, name, language, gender);
        }
    }
}
