/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for Data2 type.
 */
public class Data2 {
    private String action;
    private String agentCode;
    private String agentName;
    private String agentPassword;

    /**
     * Default constructor.
     */
    public Data2() {
    }

    /**
     * Initialization constructor.
     * @param  action  String value for action.
     * @param  agentCode  String value for agentCode.
     * @param  agentName  String value for agentName.
     * @param  agentPassword  String value for agentPassword.
     */
    public Data2(
            String action,
            String agentCode,
            String agentName,
            String agentPassword) {
        this.action = action;
        this.agentCode = agentCode;
        this.agentName = agentName;
        this.agentPassword = agentPassword;
    }

    /**
     * Getter for Action.
     * @return Returns the String
     */
    @JsonGetter("action")
    public String getAction() {
        return action;
    }

    /**
     * Setter for Action.
     * @param action Value for String
     */
    @JsonSetter("action")
    public void setAction(String action) {
        this.action = action;
    }

    /**
     * Getter for AgentCode.
     * @return Returns the String
     */
    @JsonGetter("agent_code")
    public String getAgentCode() {
        return agentCode;
    }

    /**
     * Setter for AgentCode.
     * @param agentCode Value for String
     */
    @JsonSetter("agent_code")
    public void setAgentCode(String agentCode) {
        this.agentCode = agentCode;
    }

    /**
     * Getter for AgentName.
     * @return Returns the String
     */
    @JsonGetter("agent_name")
    public String getAgentName() {
        return agentName;
    }

    /**
     * Setter for AgentName.
     * @param agentName Value for String
     */
    @JsonSetter("agent_name")
    public void setAgentName(String agentName) {
        this.agentName = agentName;
    }

    /**
     * Getter for AgentPassword.
     * @return Returns the String
     */
    @JsonGetter("agent_password")
    public String getAgentPassword() {
        return agentPassword;
    }

    /**
     * Setter for AgentPassword.
     * @param agentPassword Value for String
     */
    @JsonSetter("agent_password")
    public void setAgentPassword(String agentPassword) {
        this.agentPassword = agentPassword;
    }

    /**
     * Converts this Data2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Data2 [" + "action=" + action + ", agentCode=" + agentCode + ", agentName="
                + agentName + ", agentPassword=" + agentPassword + "]";
    }

    /**
     * Builds a new {@link Data2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Data2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(action, agentCode, agentName, agentPassword);
        return builder;
    }

    /**
     * Class to build instances of {@link Data2}.
     */
    public static class Builder {
        private String action;
        private String agentCode;
        private String agentName;
        private String agentPassword;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  action  String value for action.
         * @param  agentCode  String value for agentCode.
         * @param  agentName  String value for agentName.
         * @param  agentPassword  String value for agentPassword.
         */
        public Builder(String action, String agentCode, String agentName, String agentPassword) {
            this.action = action;
            this.agentCode = agentCode;
            this.agentName = agentName;
            this.agentPassword = agentPassword;
        }

        /**
         * Setter for action.
         * @param  action  String value for action.
         * @return Builder
         */
        public Builder action(String action) {
            this.action = action;
            return this;
        }

        /**
         * Setter for agentCode.
         * @param  agentCode  String value for agentCode.
         * @return Builder
         */
        public Builder agentCode(String agentCode) {
            this.agentCode = agentCode;
            return this;
        }

        /**
         * Setter for agentName.
         * @param  agentName  String value for agentName.
         * @return Builder
         */
        public Builder agentName(String agentName) {
            this.agentName = agentName;
            return this;
        }

        /**
         * Setter for agentPassword.
         * @param  agentPassword  String value for agentPassword.
         * @return Builder
         */
        public Builder agentPassword(String agentPassword) {
            this.agentPassword = agentPassword;
            return this;
        }

        /**
         * Builds a new {@link Data2} object using the set fields.
         * @return {@link Data2}
         */
        public Data2 build() {
            return new Data2(action, agentCode, agentName, agentPassword);
        }
    }
}
