/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for Data type.
 */
public class Data {
    private String extension;
    private String secret;
    private String deviceOwner;

    /**
     * Default constructor.
     */
    public Data() {
    }

    /**
     * Initialization constructor.
     * @param  extension  String value for extension.
     * @param  secret  String value for secret.
     * @param  deviceOwner  String value for deviceOwner.
     */
    public Data(
            String extension,
            String secret,
            String deviceOwner) {
        this.extension = extension;
        this.secret = secret;
        this.deviceOwner = deviceOwner;
    }

    /**
     * Getter for Extension.
     * @return Returns the String
     */
    @JsonGetter("extension")
    public String getExtension() {
        return extension;
    }

    /**
     * Setter for Extension.
     * @param extension Value for String
     */
    @JsonSetter("extension")
    public void setExtension(String extension) {
        this.extension = extension;
    }

    /**
     * Getter for Secret.
     * @return Returns the String
     */
    @JsonGetter("secret")
    public String getSecret() {
        return secret;
    }

    /**
     * Setter for Secret.
     * @param secret Value for String
     */
    @JsonSetter("secret")
    public void setSecret(String secret) {
        this.secret = secret;
    }

    /**
     * Getter for DeviceOwner.
     * @return Returns the String
     */
    @JsonGetter("device_owner")
    public String getDeviceOwner() {
        return deviceOwner;
    }

    /**
     * Setter for DeviceOwner.
     * @param deviceOwner Value for String
     */
    @JsonSetter("device_owner")
    public void setDeviceOwner(String deviceOwner) {
        this.deviceOwner = deviceOwner;
    }

    /**
     * Converts this Data into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Data [" + "extension=" + extension + ", secret=" + secret + ", deviceOwner="
                + deviceOwner + "]";
    }

    /**
     * Builds a new {@link Data.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Data.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(extension, secret, deviceOwner);
        return builder;
    }

    /**
     * Class to build instances of {@link Data}.
     */
    public static class Builder {
        private String extension;
        private String secret;
        private String deviceOwner;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  extension  String value for extension.
         * @param  secret  String value for secret.
         * @param  deviceOwner  String value for deviceOwner.
         */
        public Builder(String extension, String secret, String deviceOwner) {
            this.extension = extension;
            this.secret = secret;
            this.deviceOwner = deviceOwner;
        }

        /**
         * Setter for extension.
         * @param  extension  String value for extension.
         * @return Builder
         */
        public Builder extension(String extension) {
            this.extension = extension;
            return this;
        }

        /**
         * Setter for secret.
         * @param  secret  String value for secret.
         * @return Builder
         */
        public Builder secret(String secret) {
            this.secret = secret;
            return this;
        }

        /**
         * Setter for deviceOwner.
         * @param  deviceOwner  String value for deviceOwner.
         * @return Builder
         */
        public Builder deviceOwner(String deviceOwner) {
            this.deviceOwner = deviceOwner;
            return this;
        }

        /**
         * Builds a new {@link Data} object using the set fields.
         * @return {@link Data}
         */
        public Data build() {
            return new Data(extension, secret, deviceOwner);
        }
    }
}
