/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for Data11 type.
 */
public class Data11 {
    private String did;
    private int activationCost;
    private int monthlyCost;
    private String didType;
    private int active;

    /**
     * Default constructor.
     */
    public Data11() {
    }

    /**
     * Initialization constructor.
     * @param  did  String value for did.
     * @param  activationCost  int value for activationCost.
     * @param  monthlyCost  int value for monthlyCost.
     * @param  didType  String value for didType.
     * @param  active  int value for active.
     */
    public Data11(
            String did,
            int activationCost,
            int monthlyCost,
            String didType,
            int active) {
        this.did = did;
        this.activationCost = activationCost;
        this.monthlyCost = monthlyCost;
        this.didType = didType;
        this.active = active;
    }

    /**
     * Getter for Did.
     * @return Returns the String
     */
    @JsonGetter("did")
    public String getDid() {
        return did;
    }

    /**
     * Setter for Did.
     * @param did Value for String
     */
    @JsonSetter("did")
    public void setDid(String did) {
        this.did = did;
    }

    /**
     * Getter for ActivationCost.
     * @return Returns the int
     */
    @JsonGetter("activation_cost")
    public int getActivationCost() {
        return activationCost;
    }

    /**
     * Setter for ActivationCost.
     * @param activationCost Value for int
     */
    @JsonSetter("activation_cost")
    public void setActivationCost(int activationCost) {
        this.activationCost = activationCost;
    }

    /**
     * Getter for MonthlyCost.
     * @return Returns the int
     */
    @JsonGetter("monthly_cost")
    public int getMonthlyCost() {
        return monthlyCost;
    }

    /**
     * Setter for MonthlyCost.
     * @param monthlyCost Value for int
     */
    @JsonSetter("monthly_cost")
    public void setMonthlyCost(int monthlyCost) {
        this.monthlyCost = monthlyCost;
    }

    /**
     * Getter for DidType.
     * @return Returns the String
     */
    @JsonGetter("did_type")
    public String getDidType() {
        return didType;
    }

    /**
     * Setter for DidType.
     * @param didType Value for String
     */
    @JsonSetter("did_type")
    public void setDidType(String didType) {
        this.didType = didType;
    }

    /**
     * Getter for Active.
     * @return Returns the int
     */
    @JsonGetter("active")
    public int getActive() {
        return active;
    }

    /**
     * Setter for Active.
     * @param active Value for int
     */
    @JsonSetter("active")
    public void setActive(int active) {
        this.active = active;
    }

    /**
     * Converts this Data11 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Data11 [" + "did=" + did + ", activationCost=" + activationCost + ", monthlyCost="
                + monthlyCost + ", didType=" + didType + ", active=" + active + "]";
    }

    /**
     * Builds a new {@link Data11.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Data11.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(did, activationCost, monthlyCost, didType, active);
        return builder;
    }

    /**
     * Class to build instances of {@link Data11}.
     */
    public static class Builder {
        private String did;
        private int activationCost;
        private int monthlyCost;
        private String didType;
        private int active;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  did  String value for did.
         * @param  activationCost  int value for activationCost.
         * @param  monthlyCost  int value for monthlyCost.
         * @param  didType  String value for didType.
         * @param  active  int value for active.
         */
        public Builder(String did, int activationCost, int monthlyCost, String didType,
                int active) {
            this.did = did;
            this.activationCost = activationCost;
            this.monthlyCost = monthlyCost;
            this.didType = didType;
            this.active = active;
        }

        /**
         * Setter for did.
         * @param  did  String value for did.
         * @return Builder
         */
        public Builder did(String did) {
            this.did = did;
            return this;
        }

        /**
         * Setter for activationCost.
         * @param  activationCost  int value for activationCost.
         * @return Builder
         */
        public Builder activationCost(int activationCost) {
            this.activationCost = activationCost;
            return this;
        }

        /**
         * Setter for monthlyCost.
         * @param  monthlyCost  int value for monthlyCost.
         * @return Builder
         */
        public Builder monthlyCost(int monthlyCost) {
            this.monthlyCost = monthlyCost;
            return this;
        }

        /**
         * Setter for didType.
         * @param  didType  String value for didType.
         * @return Builder
         */
        public Builder didType(String didType) {
            this.didType = didType;
            return this;
        }

        /**
         * Setter for active.
         * @param  active  int value for active.
         * @return Builder
         */
        public Builder active(int active) {
            this.active = active;
            return this;
        }

        /**
         * Builds a new {@link Data11} object using the set fields.
         * @return {@link Data11}
         */
        public Data11 build() {
            return new Data11(did, activationCost, monthlyCost, didType, active);
        }
    }
}
