/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for Deleterequest type.
 */
public class Deleterequest {
    private String callerId;

    /**
     * Default constructor.
     */
    public Deleterequest() {
    }

    /**
     * Initialization constructor.
     * @param  callerId  String value for callerId.
     */
    public Deleterequest(
            String callerId) {
        this.callerId = callerId;
    }

    /**
     * Getter for CallerId.
     * @return Returns the String
     */
    @JsonGetter("caller_id")
    public String getCallerId() {
        return callerId;
    }

    /**
     * Setter for CallerId.
     * @param callerId Value for String
     */
    @JsonSetter("caller_id")
    public void setCallerId(String callerId) {
        this.callerId = callerId;
    }

    /**
     * Converts this Deleterequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Deleterequest [" + "callerId=" + callerId + "]";
    }

    /**
     * Builds a new {@link Deleterequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Deleterequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(callerId);
        return builder;
    }

    /**
     * Class to build instances of {@link Deleterequest}.
     */
    public static class Builder {
        private String callerId;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  callerId  String value for callerId.
         */
        public Builder(String callerId) {
            this.callerId = callerId;
        }

        /**
         * Setter for callerId.
         * @param  callerId  String value for callerId.
         * @return Builder
         */
        public Builder callerId(String callerId) {
            this.callerId = callerId;
            return this;
        }

        /**
         * Builds a new {@link Deleterequest} object using the set fields.
         * @return {@link Deleterequest}
         */
        public Deleterequest build() {
            return new Deleterequest(callerId);
        }
    }
}
