/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for DeviceDeleteRequest type.
 */
public class DeviceDeleteRequest {
    private String extension;

    /**
     * Default constructor.
     */
    public DeviceDeleteRequest() {
    }

    /**
     * Initialization constructor.
     * @param  extension  String value for extension.
     */
    public DeviceDeleteRequest(
            String extension) {
        this.extension = extension;
    }

    /**
     * Getter for Extension.
     * @return Returns the String
     */
    @JsonGetter("extension")
    public String getExtension() {
        return extension;
    }

    /**
     * Setter for Extension.
     * @param extension Value for String
     */
    @JsonSetter("extension")
    public void setExtension(String extension) {
        this.extension = extension;
    }

    /**
     * Converts this DeviceDeleteRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DeviceDeleteRequest [" + "extension=" + extension + "]";
    }

    /**
     * Builds a new {@link DeviceDeleteRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DeviceDeleteRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(extension);
        return builder;
    }

    /**
     * Class to build instances of {@link DeviceDeleteRequest}.
     */
    public static class Builder {
        private String extension;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  extension  String value for extension.
         */
        public Builder(String extension) {
            this.extension = extension;
        }

        /**
         * Setter for extension.
         * @param  extension  String value for extension.
         * @return Builder
         */
        public Builder extension(String extension) {
            this.extension = extension;
            return this;
        }

        /**
         * Builds a new {@link DeviceDeleteRequest} object using the set fields.
         * @return {@link DeviceDeleteRequest}
         */
        public DeviceDeleteRequest build() {
            return new DeviceDeleteRequest(extension);
        }
    }
}
