/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for DIDBuyRequest type.
 */
public class DIDBuyRequest {
    private String did;

    /**
     * Default constructor.
     */
    public DIDBuyRequest() {
    }

    /**
     * Initialization constructor.
     * @param  did  String value for did.
     */
    public DIDBuyRequest(
            String did) {
        this.did = did;
    }

    /**
     * Getter for Did.
     * @return Returns the String
     */
    @JsonGetter("did")
    public String getDid() {
        return did;
    }

    /**
     * Setter for Did.
     * @param did Value for String
     */
    @JsonSetter("did")
    public void setDid(String did) {
        this.did = did;
    }

    /**
     * Converts this DIDBuyRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DIDBuyRequest [" + "did=" + did + "]";
    }

    /**
     * Builds a new {@link DIDBuyRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DIDBuyRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(did);
        return builder;
    }

    /**
     * Class to build instances of {@link DIDBuyRequest}.
     */
    public static class Builder {
        private String did;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  did  String value for did.
         */
        public Builder(String did) {
            this.did = did;
        }

        /**
         * Setter for did.
         * @param  did  String value for did.
         * @return Builder
         */
        public Builder did(String did) {
            this.did = did;
            return this;
        }

        /**
         * Builds a new {@link DIDBuyRequest} object using the set fields.
         * @return {@link DIDBuyRequest}
         */
        public DIDBuyRequest build() {
            return new DIDBuyRequest(did);
        }
    }
}
