/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;
import java.util.List;

/**
 * This is a model class for DIDList type.
 */
public class DIDList {
    private boolean response;
    private List<Data10> data;

    /**
     * Default constructor.
     */
    public DIDList() {
    }

    /**
     * Initialization constructor.
     * @param  response  boolean value for response.
     * @param  data  List of Data10 value for data.
     */
    public DIDList(
            boolean response,
            List<Data10> data) {
        this.response = response;
        this.data = data;
    }

    /**
     * Getter for Response.
     * @return Returns the boolean
     */
    @JsonGetter("response")
    public boolean getResponse() {
        return response;
    }

    /**
     * Setter for Response.
     * @param response Value for boolean
     */
    @JsonSetter("response")
    public void setResponse(boolean response) {
        this.response = response;
    }

    /**
     * Getter for Data.
     * @return Returns the List of Data10
     */
    @JsonGetter("data")
    public List<Data10> getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for List of Data10
     */
    @JsonSetter("data")
    public void setData(List<Data10> data) {
        this.data = data;
    }

    /**
     * Converts this DIDList into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DIDList [" + "response=" + response + ", data=" + data + "]";
    }

    /**
     * Builds a new {@link DIDList.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DIDList.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(response, data);
        return builder;
    }

    /**
     * Class to build instances of {@link DIDList}.
     */
    public static class Builder {
        private boolean response;
        private List<Data10> data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  response  boolean value for response.
         * @param  data  List of Data10 value for data.
         */
        public Builder(boolean response, List<Data10> data) {
            this.response = response;
            this.data = data;
        }

        /**
         * Setter for response.
         * @param  response  boolean value for response.
         * @return Builder
         */
        public Builder response(boolean response) {
            this.response = response;
            return this;
        }

        /**
         * Setter for data.
         * @param  data  List of Data10 value for data.
         * @return Builder
         */
        public Builder data(List<Data10> data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link DIDList} object using the set fields.
         * @return {@link DIDList}
         */
        public DIDList build() {
            return new DIDList(response, data);
        }
    }
}
