/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for IncomingRoute type.
 */
public class IncomingRoute {
    private int id;
    private String transactionId;
    private String customerCode;
    private String did;
    private String destination;
    private String destinationDetail;
    private String createDate;
    private int isActive;

    /**
     * Default constructor.
     */
    public IncomingRoute() {
    }

    /**
     * Initialization constructor.
     * @param  id  int value for id.
     * @param  transactionId  String value for transactionId.
     * @param  customerCode  String value for customerCode.
     * @param  did  String value for did.
     * @param  destination  String value for destination.
     * @param  destinationDetail  String value for destinationDetail.
     * @param  createDate  String value for createDate.
     * @param  isActive  int value for isActive.
     */
    public IncomingRoute(
            int id,
            String transactionId,
            String customerCode,
            String did,
            String destination,
            String destinationDetail,
            String createDate,
            int isActive) {
        this.id = id;
        this.transactionId = transactionId;
        this.customerCode = customerCode;
        this.did = did;
        this.destination = destination;
        this.destinationDetail = destinationDetail;
        this.createDate = createDate;
        this.isActive = isActive;
    }

    /**
     * Getter for Id.
     * @return Returns the int
     */
    @JsonGetter("id")
    public int getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for int
     */
    @JsonSetter("id")
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Getter for TransactionId.
     * @return Returns the String
     */
    @JsonGetter("transaction_id")
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Setter for TransactionId.
     * @param transactionId Value for String
     */
    @JsonSetter("transaction_id")
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * Getter for CustomerCode.
     * @return Returns the String
     */
    @JsonGetter("customer_code")
    public String getCustomerCode() {
        return customerCode;
    }

    /**
     * Setter for CustomerCode.
     * @param customerCode Value for String
     */
    @JsonSetter("customer_code")
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }

    /**
     * Getter for Did.
     * @return Returns the String
     */
    @JsonGetter("did")
    public String getDid() {
        return did;
    }

    /**
     * Setter for Did.
     * @param did Value for String
     */
    @JsonSetter("did")
    public void setDid(String did) {
        this.did = did;
    }

    /**
     * Getter for Destination.
     * @return Returns the String
     */
    @JsonGetter("destination")
    public String getDestination() {
        return destination;
    }

    /**
     * Setter for Destination.
     * @param destination Value for String
     */
    @JsonSetter("destination")
    public void setDestination(String destination) {
        this.destination = destination;
    }

    /**
     * Getter for DestinationDetail.
     * @return Returns the String
     */
    @JsonGetter("destination_detail")
    public String getDestinationDetail() {
        return destinationDetail;
    }

    /**
     * Setter for DestinationDetail.
     * @param destinationDetail Value for String
     */
    @JsonSetter("destination_detail")
    public void setDestinationDetail(String destinationDetail) {
        this.destinationDetail = destinationDetail;
    }

    /**
     * Getter for CreateDate.
     * @return Returns the String
     */
    @JsonGetter("create_date")
    public String getCreateDate() {
        return createDate;
    }

    /**
     * Setter for CreateDate.
     * @param createDate Value for String
     */
    @JsonSetter("create_date")
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * Getter for IsActive.
     * @return Returns the int
     */
    @JsonGetter("isActive")
    public int getIsActive() {
        return isActive;
    }

    /**
     * Setter for IsActive.
     * @param isActive Value for int
     */
    @JsonSetter("isActive")
    public void setIsActive(int isActive) {
        this.isActive = isActive;
    }

    /**
     * Converts this IncomingRoute into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "IncomingRoute [" + "id=" + id + ", transactionId=" + transactionId
                + ", customerCode=" + customerCode + ", did=" + did + ", destination=" + destination
                + ", destinationDetail=" + destinationDetail + ", createDate=" + createDate
                + ", isActive=" + isActive + "]";
    }

    /**
     * Builds a new {@link IncomingRoute.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link IncomingRoute.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, transactionId, customerCode, did, destination,
                destinationDetail, createDate, isActive);
        return builder;
    }

    /**
     * Class to build instances of {@link IncomingRoute}.
     */
    public static class Builder {
        private int id;
        private String transactionId;
        private String customerCode;
        private String did;
        private String destination;
        private String destinationDetail;
        private String createDate;
        private int isActive;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  int value for id.
         * @param  transactionId  String value for transactionId.
         * @param  customerCode  String value for customerCode.
         * @param  did  String value for did.
         * @param  destination  String value for destination.
         * @param  destinationDetail  String value for destinationDetail.
         * @param  createDate  String value for createDate.
         * @param  isActive  int value for isActive.
         */
        public Builder(int id, String transactionId, String customerCode, String did,
                String destination, String destinationDetail, String createDate, int isActive) {
            this.id = id;
            this.transactionId = transactionId;
            this.customerCode = customerCode;
            this.did = did;
            this.destination = destination;
            this.destinationDetail = destinationDetail;
            this.createDate = createDate;
            this.isActive = isActive;
        }

        /**
         * Setter for id.
         * @param  id  int value for id.
         * @return Builder
         */
        public Builder id(int id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for transactionId.
         * @param  transactionId  String value for transactionId.
         * @return Builder
         */
        public Builder transactionId(String transactionId) {
            this.transactionId = transactionId;
            return this;
        }

        /**
         * Setter for customerCode.
         * @param  customerCode  String value for customerCode.
         * @return Builder
         */
        public Builder customerCode(String customerCode) {
            this.customerCode = customerCode;
            return this;
        }

        /**
         * Setter for did.
         * @param  did  String value for did.
         * @return Builder
         */
        public Builder did(String did) {
            this.did = did;
            return this;
        }

        /**
         * Setter for destination.
         * @param  destination  String value for destination.
         * @return Builder
         */
        public Builder destination(String destination) {
            this.destination = destination;
            return this;
        }

        /**
         * Setter for destinationDetail.
         * @param  destinationDetail  String value for destinationDetail.
         * @return Builder
         */
        public Builder destinationDetail(String destinationDetail) {
            this.destinationDetail = destinationDetail;
            return this;
        }

        /**
         * Setter for createDate.
         * @param  createDate  String value for createDate.
         * @return Builder
         */
        public Builder createDate(String createDate) {
            this.createDate = createDate;
            return this;
        }

        /**
         * Setter for isActive.
         * @param  isActive  int value for isActive.
         * @return Builder
         */
        public Builder isActive(int isActive) {
            this.isActive = isActive;
            return this;
        }

        /**
         * Builds a new {@link IncomingRoute} object using the set fields.
         * @return {@link IncomingRoute}
         */
        public IncomingRoute build() {
            return new IncomingRoute(id, transactionId, customerCode, did, destination,
                    destinationDetail, createDate, isActive);
        }
    }
}
