/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for IntentDeleteRequest type.
 */
public class IntentDeleteRequest {
    private String aiName;
    private String displayName;

    /**
     * Default constructor.
     */
    public IntentDeleteRequest() {
    }

    /**
     * Initialization constructor.
     * @param  aiName  String value for aiName.
     * @param  displayName  String value for displayName.
     */
    public IntentDeleteRequest(
            String aiName,
            String displayName) {
        this.aiName = aiName;
        this.displayName = displayName;
    }

    /**
     * Getter for AiName.
     * @return Returns the String
     */
    @JsonGetter("ai_name")
    public String getAiName() {
        return aiName;
    }

    /**
     * Setter for AiName.
     * @param aiName Value for String
     */
    @JsonSetter("ai_name")
    public void setAiName(String aiName) {
        this.aiName = aiName;
    }

    /**
     * Getter for DisplayName.
     * @return Returns the String
     */
    @JsonGetter("display_name")
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Setter for DisplayName.
     * @param displayName Value for String
     */
    @JsonSetter("display_name")
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /**
     * Converts this IntentDeleteRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "IntentDeleteRequest [" + "aiName=" + aiName + ", displayName=" + displayName + "]";
    }

    /**
     * Builds a new {@link IntentDeleteRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link IntentDeleteRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(aiName, displayName);
        return builder;
    }

    /**
     * Class to build instances of {@link IntentDeleteRequest}.
     */
    public static class Builder {
        private String aiName;
        private String displayName;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  aiName  String value for aiName.
         * @param  displayName  String value for displayName.
         */
        public Builder(String aiName, String displayName) {
            this.aiName = aiName;
            this.displayName = displayName;
        }

        /**
         * Setter for aiName.
         * @param  aiName  String value for aiName.
         * @return Builder
         */
        public Builder aiName(String aiName) {
            this.aiName = aiName;
            return this;
        }

        /**
         * Setter for displayName.
         * @param  displayName  String value for displayName.
         * @return Builder
         */
        public Builder displayName(String displayName) {
            this.displayName = displayName;
            return this;
        }

        /**
         * Builds a new {@link IntentDeleteRequest} object using the set fields.
         * @return {@link IntentDeleteRequest}
         */
        public IntentDeleteRequest build() {
            return new IntentDeleteRequest(aiName, displayName);
        }
    }
}
