/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for IntentEditRequest type.
 */
public class IntentEditRequest {
    private String aiName;
    private String displayName;
    private String trainingPhrases;
    private String messageTexts;

    /**
     * Default constructor.
     */
    public IntentEditRequest() {
    }

    /**
     * Initialization constructor.
     * @param  aiName  String value for aiName.
     * @param  displayName  String value for displayName.
     * @param  trainingPhrases  String value for trainingPhrases.
     * @param  messageTexts  String value for messageTexts.
     */
    public IntentEditRequest(
            String aiName,
            String displayName,
            String trainingPhrases,
            String messageTexts) {
        this.aiName = aiName;
        this.displayName = displayName;
        this.trainingPhrases = trainingPhrases;
        this.messageTexts = messageTexts;
    }

    /**
     * Getter for AiName.
     * @return Returns the String
     */
    @JsonGetter("ai_name")
    public String getAiName() {
        return aiName;
    }

    /**
     * Setter for AiName.
     * @param aiName Value for String
     */
    @JsonSetter("ai_name")
    public void setAiName(String aiName) {
        this.aiName = aiName;
    }

    /**
     * Getter for DisplayName.
     * @return Returns the String
     */
    @JsonGetter("display_name")
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Setter for DisplayName.
     * @param displayName Value for String
     */
    @JsonSetter("display_name")
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /**
     * Getter for TrainingPhrases.
     * @return Returns the String
     */
    @JsonGetter("training_phrases")
    public String getTrainingPhrases() {
        return trainingPhrases;
    }

    /**
     * Setter for TrainingPhrases.
     * @param trainingPhrases Value for String
     */
    @JsonSetter("training_phrases")
    public void setTrainingPhrases(String trainingPhrases) {
        this.trainingPhrases = trainingPhrases;
    }

    /**
     * Getter for MessageTexts.
     * @return Returns the String
     */
    @JsonGetter("message_texts")
    public String getMessageTexts() {
        return messageTexts;
    }

    /**
     * Setter for MessageTexts.
     * @param messageTexts Value for String
     */
    @JsonSetter("message_texts")
    public void setMessageTexts(String messageTexts) {
        this.messageTexts = messageTexts;
    }

    /**
     * Converts this IntentEditRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "IntentEditRequest [" + "aiName=" + aiName + ", displayName=" + displayName
                + ", trainingPhrases=" + trainingPhrases + ", messageTexts=" + messageTexts + "]";
    }

    /**
     * Builds a new {@link IntentEditRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link IntentEditRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(aiName, displayName, trainingPhrases, messageTexts);
        return builder;
    }

    /**
     * Class to build instances of {@link IntentEditRequest}.
     */
    public static class Builder {
        private String aiName;
        private String displayName;
        private String trainingPhrases;
        private String messageTexts;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  aiName  String value for aiName.
         * @param  displayName  String value for displayName.
         * @param  trainingPhrases  String value for trainingPhrases.
         * @param  messageTexts  String value for messageTexts.
         */
        public Builder(String aiName, String displayName, String trainingPhrases,
                String messageTexts) {
            this.aiName = aiName;
            this.displayName = displayName;
            this.trainingPhrases = trainingPhrases;
            this.messageTexts = messageTexts;
        }

        /**
         * Setter for aiName.
         * @param  aiName  String value for aiName.
         * @return Builder
         */
        public Builder aiName(String aiName) {
            this.aiName = aiName;
            return this;
        }

        /**
         * Setter for displayName.
         * @param  displayName  String value for displayName.
         * @return Builder
         */
        public Builder displayName(String displayName) {
            this.displayName = displayName;
            return this;
        }

        /**
         * Setter for trainingPhrases.
         * @param  trainingPhrases  String value for trainingPhrases.
         * @return Builder
         */
        public Builder trainingPhrases(String trainingPhrases) {
            this.trainingPhrases = trainingPhrases;
            return this;
        }

        /**
         * Setter for messageTexts.
         * @param  messageTexts  String value for messageTexts.
         * @return Builder
         */
        public Builder messageTexts(String messageTexts) {
            this.messageTexts = messageTexts;
            return this;
        }

        /**
         * Builds a new {@link IntentEditRequest} object using the set fields.
         * @return {@link IntentEditRequest}
         */
        public IntentEditRequest build() {
            return new IntentEditRequest(aiName, displayName, trainingPhrases, messageTexts);
        }
    }
}
