/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for IVRDeleteRequest type.
 */
public class IVRDeleteRequest {
    private String ivrName;

    /**
     * Default constructor.
     */
    public IVRDeleteRequest() {
    }

    /**
     * Initialization constructor.
     * @param  ivrName  String value for ivrName.
     */
    public IVRDeleteRequest(
            String ivrName) {
        this.ivrName = ivrName;
    }

    /**
     * Getter for IvrName.
     * @return Returns the String
     */
    @JsonGetter("ivr_name")
    public String getIvrName() {
        return ivrName;
    }

    /**
     * Setter for IvrName.
     * @param ivrName Value for String
     */
    @JsonSetter("ivr_name")
    public void setIvrName(String ivrName) {
        this.ivrName = ivrName;
    }

    /**
     * Converts this IVRDeleteRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "IVRDeleteRequest [" + "ivrName=" + ivrName + "]";
    }

    /**
     * Builds a new {@link IVRDeleteRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link IVRDeleteRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(ivrName);
        return builder;
    }

    /**
     * Class to build instances of {@link IVRDeleteRequest}.
     */
    public static class Builder {
        private String ivrName;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  ivrName  String value for ivrName.
         */
        public Builder(String ivrName) {
            this.ivrName = ivrName;
        }

        /**
         * Setter for ivrName.
         * @param  ivrName  String value for ivrName.
         * @return Builder
         */
        public Builder ivrName(String ivrName) {
            this.ivrName = ivrName;
            return this;
        }

        /**
         * Builds a new {@link IVRDeleteRequest} object using the set fields.
         * @return {@link IVRDeleteRequest}
         */
        public IVRDeleteRequest build() {
            return new IVRDeleteRequest(ivrName);
        }
    }
}
