/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for Member type.
 */
public class Member {
    private String member;

    /**
     * Default constructor.
     */
    public Member() {
    }

    /**
     * Initialization constructor.
     * @param  member  String value for member.
     */
    public Member(
            String member) {
        this.member = member;
    }

    /**
     * Getter for Member.
     * @return Returns the String
     */
    @JsonGetter("member")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMember() {
        return member;
    }

    /**
     * Setter for Member.
     * @param member Value for String
     */
    @JsonSetter("member")
    public void setMember(String member) {
        this.member = member;
    }

    /**
     * Converts this Member into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Member [" + "member=" + member + "]";
    }

    /**
     * Builds a new {@link Member.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Member.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .member(getMember());
        return builder;
    }

    /**
     * Class to build instances of {@link Member}.
     */
    public static class Builder {
        private String member;



        /**
         * Setter for member.
         * @param  member  String value for member.
         * @return Builder
         */
        public Builder member(String member) {
            this.member = member;
            return this;
        }

        /**
         * Builds a new {@link Member} object using the set fields.
         * @return {@link Member}
         */
        public Member build() {
            return new Member(member);
        }
    }
}
