/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for OutgoingRoute type.
 */
public class OutgoingRoute {
    private int id;
    private String customerCode;
    private String extension;
    private String routeTo;
    private String routeDetail;
    private String techPrefix;
    private String createDate;
    private int isActive;

    /**
     * Default constructor.
     */
    public OutgoingRoute() {
    }

    /**
     * Initialization constructor.
     * @param  id  int value for id.
     * @param  customerCode  String value for customerCode.
     * @param  extension  String value for extension.
     * @param  routeTo  String value for routeTo.
     * @param  routeDetail  String value for routeDetail.
     * @param  techPrefix  String value for techPrefix.
     * @param  createDate  String value for createDate.
     * @param  isActive  int value for isActive.
     */
    public OutgoingRoute(
            int id,
            String customerCode,
            String extension,
            String routeTo,
            String routeDetail,
            String techPrefix,
            String createDate,
            int isActive) {
        this.id = id;
        this.customerCode = customerCode;
        this.extension = extension;
        this.routeTo = routeTo;
        this.routeDetail = routeDetail;
        this.techPrefix = techPrefix;
        this.createDate = createDate;
        this.isActive = isActive;
    }

    /**
     * Getter for Id.
     * @return Returns the int
     */
    @JsonGetter("id")
    public int getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for int
     */
    @JsonSetter("id")
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Getter for CustomerCode.
     * @return Returns the String
     */
    @JsonGetter("customer_code")
    public String getCustomerCode() {
        return customerCode;
    }

    /**
     * Setter for CustomerCode.
     * @param customerCode Value for String
     */
    @JsonSetter("customer_code")
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }

    /**
     * Getter for Extension.
     * @return Returns the String
     */
    @JsonGetter("extension")
    public String getExtension() {
        return extension;
    }

    /**
     * Setter for Extension.
     * @param extension Value for String
     */
    @JsonSetter("extension")
    public void setExtension(String extension) {
        this.extension = extension;
    }

    /**
     * Getter for RouteTo.
     * @return Returns the String
     */
    @JsonGetter("route_to")
    public String getRouteTo() {
        return routeTo;
    }

    /**
     * Setter for RouteTo.
     * @param routeTo Value for String
     */
    @JsonSetter("route_to")
    public void setRouteTo(String routeTo) {
        this.routeTo = routeTo;
    }

    /**
     * Getter for RouteDetail.
     * @return Returns the String
     */
    @JsonGetter("route_detail")
    public String getRouteDetail() {
        return routeDetail;
    }

    /**
     * Setter for RouteDetail.
     * @param routeDetail Value for String
     */
    @JsonSetter("route_detail")
    public void setRouteDetail(String routeDetail) {
        this.routeDetail = routeDetail;
    }

    /**
     * Getter for TechPrefix.
     * @return Returns the String
     */
    @JsonGetter("tech_prefix")
    public String getTechPrefix() {
        return techPrefix;
    }

    /**
     * Setter for TechPrefix.
     * @param techPrefix Value for String
     */
    @JsonSetter("tech_prefix")
    public void setTechPrefix(String techPrefix) {
        this.techPrefix = techPrefix;
    }

    /**
     * Getter for CreateDate.
     * @return Returns the String
     */
    @JsonGetter("create_date")
    public String getCreateDate() {
        return createDate;
    }

    /**
     * Setter for CreateDate.
     * @param createDate Value for String
     */
    @JsonSetter("create_date")
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * Getter for IsActive.
     * @return Returns the int
     */
    @JsonGetter("isActive")
    public int getIsActive() {
        return isActive;
    }

    /**
     * Setter for IsActive.
     * @param isActive Value for int
     */
    @JsonSetter("isActive")
    public void setIsActive(int isActive) {
        this.isActive = isActive;
    }

    /**
     * Converts this OutgoingRoute into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "OutgoingRoute [" + "id=" + id + ", customerCode=" + customerCode + ", extension="
                + extension + ", routeTo=" + routeTo + ", routeDetail=" + routeDetail
                + ", techPrefix=" + techPrefix + ", createDate=" + createDate + ", isActive="
                + isActive + "]";
    }

    /**
     * Builds a new {@link OutgoingRoute.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link OutgoingRoute.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, customerCode, extension, routeTo, routeDetail, techPrefix,
                createDate, isActive);
        return builder;
    }

    /**
     * Class to build instances of {@link OutgoingRoute}.
     */
    public static class Builder {
        private int id;
        private String customerCode;
        private String extension;
        private String routeTo;
        private String routeDetail;
        private String techPrefix;
        private String createDate;
        private int isActive;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  int value for id.
         * @param  customerCode  String value for customerCode.
         * @param  extension  String value for extension.
         * @param  routeTo  String value for routeTo.
         * @param  routeDetail  String value for routeDetail.
         * @param  techPrefix  String value for techPrefix.
         * @param  createDate  String value for createDate.
         * @param  isActive  int value for isActive.
         */
        public Builder(int id, String customerCode, String extension, String routeTo,
                String routeDetail, String techPrefix, String createDate, int isActive) {
            this.id = id;
            this.customerCode = customerCode;
            this.extension = extension;
            this.routeTo = routeTo;
            this.routeDetail = routeDetail;
            this.techPrefix = techPrefix;
            this.createDate = createDate;
            this.isActive = isActive;
        }

        /**
         * Setter for id.
         * @param  id  int value for id.
         * @return Builder
         */
        public Builder id(int id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for customerCode.
         * @param  customerCode  String value for customerCode.
         * @return Builder
         */
        public Builder customerCode(String customerCode) {
            this.customerCode = customerCode;
            return this;
        }

        /**
         * Setter for extension.
         * @param  extension  String value for extension.
         * @return Builder
         */
        public Builder extension(String extension) {
            this.extension = extension;
            return this;
        }

        /**
         * Setter for routeTo.
         * @param  routeTo  String value for routeTo.
         * @return Builder
         */
        public Builder routeTo(String routeTo) {
            this.routeTo = routeTo;
            return this;
        }

        /**
         * Setter for routeDetail.
         * @param  routeDetail  String value for routeDetail.
         * @return Builder
         */
        public Builder routeDetail(String routeDetail) {
            this.routeDetail = routeDetail;
            return this;
        }

        /**
         * Setter for techPrefix.
         * @param  techPrefix  String value for techPrefix.
         * @return Builder
         */
        public Builder techPrefix(String techPrefix) {
            this.techPrefix = techPrefix;
            return this;
        }

        /**
         * Setter for createDate.
         * @param  createDate  String value for createDate.
         * @return Builder
         */
        public Builder createDate(String createDate) {
            this.createDate = createDate;
            return this;
        }

        /**
         * Setter for isActive.
         * @param  isActive  int value for isActive.
         * @return Builder
         */
        public Builder isActive(int isActive) {
            this.isActive = isActive;
            return this;
        }

        /**
         * Builds a new {@link OutgoingRoute} object using the set fields.
         * @return {@link OutgoingRoute}
         */
        public OutgoingRoute build() {
            return new OutgoingRoute(id, customerCode, extension, routeTo, routeDetail, techPrefix,
                    createDate, isActive);
        }
    }
}
