/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for QueueDeleteRequest type.
 */
public class QueueDeleteRequest {
    private String queueName;

    /**
     * Default constructor.
     */
    public QueueDeleteRequest() {
    }

    /**
     * Initialization constructor.
     * @param  queueName  String value for queueName.
     */
    public QueueDeleteRequest(
            String queueName) {
        this.queueName = queueName;
    }

    /**
     * Getter for QueueName.
     * @return Returns the String
     */
    @JsonGetter("queue_name")
    public String getQueueName() {
        return queueName;
    }

    /**
     * Setter for QueueName.
     * @param queueName Value for String
     */
    @JsonSetter("queue_name")
    public void setQueueName(String queueName) {
        this.queueName = queueName;
    }

    /**
     * Converts this QueueDeleteRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "QueueDeleteRequest [" + "queueName=" + queueName + "]";
    }

    /**
     * Builds a new {@link QueueDeleteRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link QueueDeleteRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(queueName);
        return builder;
    }

    /**
     * Class to build instances of {@link QueueDeleteRequest}.
     */
    public static class Builder {
        private String queueName;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  queueName  String value for queueName.
         */
        public Builder(String queueName) {
            this.queueName = queueName;
        }

        /**
         * Setter for queueName.
         * @param  queueName  String value for queueName.
         * @return Builder
         */
        public Builder queueName(String queueName) {
            this.queueName = queueName;
            return this;
        }

        /**
         * Builds a new {@link QueueDeleteRequest} object using the set fields.
         * @return {@link QueueDeleteRequest}
         */
        public QueueDeleteRequest build() {
            return new QueueDeleteRequest(queueName);
        }
    }
}
