/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for QueueNewRequest type.
 */
public class QueueNewRequest {
    private String queueName;
    private String ringStrategy;

    /**
     * Default constructor.
     */
    public QueueNewRequest() {
    }

    /**
     * Initialization constructor.
     * @param  queueName  String value for queueName.
     * @param  ringStrategy  String value for ringStrategy.
     */
    public QueueNewRequest(
            String queueName,
            String ringStrategy) {
        this.queueName = queueName;
        this.ringStrategy = ringStrategy;
    }

    /**
     * Getter for QueueName.
     * @return Returns the String
     */
    @JsonGetter("queue_name")
    public String getQueueName() {
        return queueName;
    }

    /**
     * Setter for QueueName.
     * @param queueName Value for String
     */
    @JsonSetter("queue_name")
    public void setQueueName(String queueName) {
        this.queueName = queueName;
    }

    /**
     * Getter for RingStrategy.
     * @return Returns the String
     */
    @JsonGetter("ring_strategy")
    public String getRingStrategy() {
        return ringStrategy;
    }

    /**
     * Setter for RingStrategy.
     * @param ringStrategy Value for String
     */
    @JsonSetter("ring_strategy")
    public void setRingStrategy(String ringStrategy) {
        this.ringStrategy = ringStrategy;
    }

    /**
     * Converts this QueueNewRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "QueueNewRequest [" + "queueName=" + queueName + ", ringStrategy=" + ringStrategy
                + "]";
    }

    /**
     * Builds a new {@link QueueNewRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link QueueNewRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(queueName, ringStrategy);
        return builder;
    }

    /**
     * Class to build instances of {@link QueueNewRequest}.
     */
    public static class Builder {
        private String queueName;
        private String ringStrategy;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  queueName  String value for queueName.
         * @param  ringStrategy  String value for ringStrategy.
         */
        public Builder(String queueName, String ringStrategy) {
            this.queueName = queueName;
            this.ringStrategy = ringStrategy;
        }

        /**
         * Setter for queueName.
         * @param  queueName  String value for queueName.
         * @return Builder
         */
        public Builder queueName(String queueName) {
            this.queueName = queueName;
            return this;
        }

        /**
         * Setter for ringStrategy.
         * @param  ringStrategy  String value for ringStrategy.
         * @return Builder
         */
        public Builder ringStrategy(String ringStrategy) {
            this.ringStrategy = ringStrategy;
            return this;
        }

        /**
         * Builds a new {@link QueueNewRequest} object using the set fields.
         * @return {@link QueueNewRequest}
         */
        public QueueNewRequest build() {
            return new QueueNewRequest(queueName, ringStrategy);
        }
    }
}
