/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for Rcode type.
 */
public class Rcode {
    private String transactionId;
    private String callbackKey;
    private String destination;
    private String textToSpeech;
    private String language;
    private String gender;
    private String voiceRepeat;
    private String externalId;
    private String callbackUrl;

    /**
     * Default constructor.
     */
    public Rcode() {
    }

    /**
     * Initialization constructor.
     * @param  transactionId  String value for transactionId.
     * @param  callbackKey  String value for callbackKey.
     * @param  destination  String value for destination.
     * @param  textToSpeech  String value for textToSpeech.
     * @param  language  String value for language.
     * @param  gender  String value for gender.
     * @param  voiceRepeat  String value for voiceRepeat.
     * @param  externalId  String value for externalId.
     * @param  callbackUrl  String value for callbackUrl.
     */
    public Rcode(
            String transactionId,
            String callbackKey,
            String destination,
            String textToSpeech,
            String language,
            String gender,
            String voiceRepeat,
            String externalId,
            String callbackUrl) {
        this.transactionId = transactionId;
        this.callbackKey = callbackKey;
        this.destination = destination;
        this.textToSpeech = textToSpeech;
        this.language = language;
        this.gender = gender;
        this.voiceRepeat = voiceRepeat;
        this.externalId = externalId;
        this.callbackUrl = callbackUrl;
    }

    /**
     * Getter for TransactionId.
     * @return Returns the String
     */
    @JsonGetter("transaction_id")
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Setter for TransactionId.
     * @param transactionId Value for String
     */
    @JsonSetter("transaction_id")
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * Getter for CallbackKey.
     * @return Returns the String
     */
    @JsonGetter("callback_key")
    public String getCallbackKey() {
        return callbackKey;
    }

    /**
     * Setter for CallbackKey.
     * @param callbackKey Value for String
     */
    @JsonSetter("callback_key")
    public void setCallbackKey(String callbackKey) {
        this.callbackKey = callbackKey;
    }

    /**
     * Getter for Destination.
     * @return Returns the String
     */
    @JsonGetter("destination")
    public String getDestination() {
        return destination;
    }

    /**
     * Setter for Destination.
     * @param destination Value for String
     */
    @JsonSetter("destination")
    public void setDestination(String destination) {
        this.destination = destination;
    }

    /**
     * Getter for TextToSpeech.
     * @return Returns the String
     */
    @JsonGetter("text_to_speech")
    public String getTextToSpeech() {
        return textToSpeech;
    }

    /**
     * Setter for TextToSpeech.
     * @param textToSpeech Value for String
     */
    @JsonSetter("text_to_speech")
    public void setTextToSpeech(String textToSpeech) {
        this.textToSpeech = textToSpeech;
    }

    /**
     * Getter for Language.
     * @return Returns the String
     */
    @JsonGetter("language")
    public String getLanguage() {
        return language;
    }

    /**
     * Setter for Language.
     * @param language Value for String
     */
    @JsonSetter("language")
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * Getter for Gender.
     * @return Returns the String
     */
    @JsonGetter("gender")
    public String getGender() {
        return gender;
    }

    /**
     * Setter for Gender.
     * @param gender Value for String
     */
    @JsonSetter("gender")
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * Getter for VoiceRepeat.
     * @return Returns the String
     */
    @JsonGetter("VoiceRepeat")
    public String getVoiceRepeat() {
        return voiceRepeat;
    }

    /**
     * Setter for VoiceRepeat.
     * @param voiceRepeat Value for String
     */
    @JsonSetter("VoiceRepeat")
    public void setVoiceRepeat(String voiceRepeat) {
        this.voiceRepeat = voiceRepeat;
    }

    /**
     * Getter for ExternalId.
     * @return Returns the String
     */
    @JsonGetter("external_id")
    public String getExternalId() {
        return externalId;
    }

    /**
     * Setter for ExternalId.
     * @param externalId Value for String
     */
    @JsonSetter("external_id")
    public void setExternalId(String externalId) {
        this.externalId = externalId;
    }

    /**
     * Getter for CallbackUrl.
     * @return Returns the String
     */
    @JsonGetter("callback_url")
    public String getCallbackUrl() {
        return callbackUrl;
    }

    /**
     * Setter for CallbackUrl.
     * @param callbackUrl Value for String
     */
    @JsonSetter("callback_url")
    public void setCallbackUrl(String callbackUrl) {
        this.callbackUrl = callbackUrl;
    }

    /**
     * Converts this Rcode into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Rcode [" + "transactionId=" + transactionId + ", callbackKey=" + callbackKey
                + ", destination=" + destination + ", textToSpeech=" + textToSpeech + ", language="
                + language + ", gender=" + gender + ", voiceRepeat=" + voiceRepeat + ", externalId="
                + externalId + ", callbackUrl=" + callbackUrl + "]";
    }

    /**
     * Builds a new {@link Rcode.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Rcode.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(transactionId, callbackKey, destination, textToSpeech,
                language, gender, voiceRepeat, externalId, callbackUrl);
        return builder;
    }

    /**
     * Class to build instances of {@link Rcode}.
     */
    public static class Builder {
        private String transactionId;
        private String callbackKey;
        private String destination;
        private String textToSpeech;
        private String language;
        private String gender;
        private String voiceRepeat;
        private String externalId;
        private String callbackUrl;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  transactionId  String value for transactionId.
         * @param  callbackKey  String value for callbackKey.
         * @param  destination  String value for destination.
         * @param  textToSpeech  String value for textToSpeech.
         * @param  language  String value for language.
         * @param  gender  String value for gender.
         * @param  voiceRepeat  String value for voiceRepeat.
         * @param  externalId  String value for externalId.
         * @param  callbackUrl  String value for callbackUrl.
         */
        public Builder(String transactionId, String callbackKey, String destination,
                String textToSpeech, String language, String gender, String voiceRepeat,
                String externalId, String callbackUrl) {
            this.transactionId = transactionId;
            this.callbackKey = callbackKey;
            this.destination = destination;
            this.textToSpeech = textToSpeech;
            this.language = language;
            this.gender = gender;
            this.voiceRepeat = voiceRepeat;
            this.externalId = externalId;
            this.callbackUrl = callbackUrl;
        }

        /**
         * Setter for transactionId.
         * @param  transactionId  String value for transactionId.
         * @return Builder
         */
        public Builder transactionId(String transactionId) {
            this.transactionId = transactionId;
            return this;
        }

        /**
         * Setter for callbackKey.
         * @param  callbackKey  String value for callbackKey.
         * @return Builder
         */
        public Builder callbackKey(String callbackKey) {
            this.callbackKey = callbackKey;
            return this;
        }

        /**
         * Setter for destination.
         * @param  destination  String value for destination.
         * @return Builder
         */
        public Builder destination(String destination) {
            this.destination = destination;
            return this;
        }

        /**
         * Setter for textToSpeech.
         * @param  textToSpeech  String value for textToSpeech.
         * @return Builder
         */
        public Builder textToSpeech(String textToSpeech) {
            this.textToSpeech = textToSpeech;
            return this;
        }

        /**
         * Setter for language.
         * @param  language  String value for language.
         * @return Builder
         */
        public Builder language(String language) {
            this.language = language;
            return this;
        }

        /**
         * Setter for gender.
         * @param  gender  String value for gender.
         * @return Builder
         */
        public Builder gender(String gender) {
            this.gender = gender;
            return this;
        }

        /**
         * Setter for voiceRepeat.
         * @param  voiceRepeat  String value for voiceRepeat.
         * @return Builder
         */
        public Builder voiceRepeat(String voiceRepeat) {
            this.voiceRepeat = voiceRepeat;
            return this;
        }

        /**
         * Setter for externalId.
         * @param  externalId  String value for externalId.
         * @return Builder
         */
        public Builder externalId(String externalId) {
            this.externalId = externalId;
            return this;
        }

        /**
         * Setter for callbackUrl.
         * @param  callbackUrl  String value for callbackUrl.
         * @return Builder
         */
        public Builder callbackUrl(String callbackUrl) {
            this.callbackUrl = callbackUrl;
            return this;
        }

        /**
         * Builds a new {@link Rcode} object using the set fields.
         * @return {@link Rcode}
         */
        public Rcode build() {
            return new Rcode(transactionId, callbackKey, destination, textToSpeech, language,
                    gender, voiceRepeat, externalId, callbackUrl);
        }
    }
}
