/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for Requestrequest type.
 */
public class Requestrequest {
    private String callerId;

    /**
     * Default constructor.
     */
    public Requestrequest() {
    }

    /**
     * Initialization constructor.
     * @param  callerId  String value for callerId.
     */
    public Requestrequest(
            String callerId) {
        this.callerId = callerId;
    }

    /**
     * Getter for CallerId.
     * @return Returns the String
     */
    @JsonGetter("caller_id")
    public String getCallerId() {
        return callerId;
    }

    /**
     * Setter for CallerId.
     * @param callerId Value for String
     */
    @JsonSetter("caller_id")
    public void setCallerId(String callerId) {
        this.callerId = callerId;
    }

    /**
     * Converts this Requestrequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Requestrequest [" + "callerId=" + callerId + "]";
    }

    /**
     * Builds a new {@link Requestrequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Requestrequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(callerId);
        return builder;
    }

    /**
     * Class to build instances of {@link Requestrequest}.
     */
    public static class Builder {
        private String callerId;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  callerId  String value for callerId.
         */
        public Builder(String callerId) {
            this.callerId = callerId;
        }

        /**
         * Setter for callerId.
         * @param  callerId  String value for callerId.
         * @return Builder
         */
        public Builder callerId(String callerId) {
            this.callerId = callerId;
            return this;
        }

        /**
         * Builds a new {@link Requestrequest} object using the set fields.
         * @return {@link Requestrequest}
         */
        public Requestrequest build() {
            return new Requestrequest(callerId);
        }
    }
}
