/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for Request type.
 */
public class Request {
    private boolean response;
    private String callerId;
    private int isActive;

    /**
     * Default constructor.
     */
    public Request() {
    }

    /**
     * Initialization constructor.
     * @param  response  boolean value for response.
     * @param  callerId  String value for callerId.
     * @param  isActive  int value for isActive.
     */
    public Request(
            boolean response,
            String callerId,
            int isActive) {
        this.response = response;
        this.callerId = callerId;
        this.isActive = isActive;
    }

    /**
     * Getter for Response.
     * @return Returns the boolean
     */
    @JsonGetter("response")
    public boolean getResponse() {
        return response;
    }

    /**
     * Setter for Response.
     * @param response Value for boolean
     */
    @JsonSetter("response")
    public void setResponse(boolean response) {
        this.response = response;
    }

    /**
     * Getter for CallerId.
     * @return Returns the String
     */
    @JsonGetter("caller_id")
    public String getCallerId() {
        return callerId;
    }

    /**
     * Setter for CallerId.
     * @param callerId Value for String
     */
    @JsonSetter("caller_id")
    public void setCallerId(String callerId) {
        this.callerId = callerId;
    }

    /**
     * Getter for IsActive.
     * @return Returns the int
     */
    @JsonGetter("isActive")
    public int getIsActive() {
        return isActive;
    }

    /**
     * Setter for IsActive.
     * @param isActive Value for int
     */
    @JsonSetter("isActive")
    public void setIsActive(int isActive) {
        this.isActive = isActive;
    }

    /**
     * Converts this Request into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Request [" + "response=" + response + ", callerId=" + callerId + ", isActive="
                + isActive + "]";
    }

    /**
     * Builds a new {@link Request.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Request.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(response, callerId, isActive);
        return builder;
    }

    /**
     * Class to build instances of {@link Request}.
     */
    public static class Builder {
        private boolean response;
        private String callerId;
        private int isActive;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  response  boolean value for response.
         * @param  callerId  String value for callerId.
         * @param  isActive  int value for isActive.
         */
        public Builder(boolean response, String callerId, int isActive) {
            this.response = response;
            this.callerId = callerId;
            this.isActive = isActive;
        }

        /**
         * Setter for response.
         * @param  response  boolean value for response.
         * @return Builder
         */
        public Builder response(boolean response) {
            this.response = response;
            return this;
        }

        /**
         * Setter for callerId.
         * @param  callerId  String value for callerId.
         * @return Builder
         */
        public Builder callerId(String callerId) {
            this.callerId = callerId;
            return this;
        }

        /**
         * Setter for isActive.
         * @param  isActive  int value for isActive.
         * @return Builder
         */
        public Builder isActive(int isActive) {
            this.isActive = isActive;
            return this;
        }

        /**
         * Builds a new {@link Request} object using the set fields.
         * @return {@link Request}
         */
        public Request build() {
            return new Request(response, callerId, isActive);
        }
    }
}
