/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for RouteIncomingRequest type.
 */
public class RouteIncomingRequest {
    private String did;
    private String destination;
    private String destinationDetail;

    /**
     * Default constructor.
     */
    public RouteIncomingRequest() {
    }

    /**
     * Initialization constructor.
     * @param  did  String value for did.
     * @param  destination  String value for destination.
     * @param  destinationDetail  String value for destinationDetail.
     */
    public RouteIncomingRequest(
            String did,
            String destination,
            String destinationDetail) {
        this.did = did;
        this.destination = destination;
        this.destinationDetail = destinationDetail;
    }

    /**
     * Getter for Did.
     * @return Returns the String
     */
    @JsonGetter("did")
    public String getDid() {
        return did;
    }

    /**
     * Setter for Did.
     * @param did Value for String
     */
    @JsonSetter("did")
    public void setDid(String did) {
        this.did = did;
    }

    /**
     * Getter for Destination.
     * @return Returns the String
     */
    @JsonGetter("destination")
    public String getDestination() {
        return destination;
    }

    /**
     * Setter for Destination.
     * @param destination Value for String
     */
    @JsonSetter("destination")
    public void setDestination(String destination) {
        this.destination = destination;
    }

    /**
     * Getter for DestinationDetail.
     * @return Returns the String
     */
    @JsonGetter("destination_detail")
    public String getDestinationDetail() {
        return destinationDetail;
    }

    /**
     * Setter for DestinationDetail.
     * @param destinationDetail Value for String
     */
    @JsonSetter("destination_detail")
    public void setDestinationDetail(String destinationDetail) {
        this.destinationDetail = destinationDetail;
    }

    /**
     * Converts this RouteIncomingRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RouteIncomingRequest [" + "did=" + did + ", destination=" + destination
                + ", destinationDetail=" + destinationDetail + "]";
    }

    /**
     * Builds a new {@link RouteIncomingRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RouteIncomingRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(did, destination, destinationDetail);
        return builder;
    }

    /**
     * Class to build instances of {@link RouteIncomingRequest}.
     */
    public static class Builder {
        private String did;
        private String destination;
        private String destinationDetail;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  did  String value for did.
         * @param  destination  String value for destination.
         * @param  destinationDetail  String value for destinationDetail.
         */
        public Builder(String did, String destination, String destinationDetail) {
            this.did = did;
            this.destination = destination;
            this.destinationDetail = destinationDetail;
        }

        /**
         * Setter for did.
         * @param  did  String value for did.
         * @return Builder
         */
        public Builder did(String did) {
            this.did = did;
            return this;
        }

        /**
         * Setter for destination.
         * @param  destination  String value for destination.
         * @return Builder
         */
        public Builder destination(String destination) {
            this.destination = destination;
            return this;
        }

        /**
         * Setter for destinationDetail.
         * @param  destinationDetail  String value for destinationDetail.
         * @return Builder
         */
        public Builder destinationDetail(String destinationDetail) {
            this.destinationDetail = destinationDetail;
            return this;
        }

        /**
         * Builds a new {@link RouteIncomingRequest} object using the set fields.
         * @return {@link RouteIncomingRequest}
         */
        public RouteIncomingRequest build() {
            return new RouteIncomingRequest(did, destination, destinationDetail);
        }
    }
}
