/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for RouteOutgoingRequest type.
 */
public class RouteOutgoingRequest {
    private String routeName;
    private String device;
    private String routeTo;
    private String routeDetail;
    private String routePrefix;

    /**
     * Default constructor.
     */
    public RouteOutgoingRequest() {
    }

    /**
     * Initialization constructor.
     * @param  routeName  String value for routeName.
     * @param  device  String value for device.
     * @param  routeTo  String value for routeTo.
     * @param  routeDetail  String value for routeDetail.
     * @param  routePrefix  String value for routePrefix.
     */
    public RouteOutgoingRequest(
            String routeName,
            String device,
            String routeTo,
            String routeDetail,
            String routePrefix) {
        this.routeName = routeName;
        this.device = device;
        this.routeTo = routeTo;
        this.routeDetail = routeDetail;
        this.routePrefix = routePrefix;
    }

    /**
     * Getter for RouteName.
     * @return Returns the String
     */
    @JsonGetter("route_name")
    public String getRouteName() {
        return routeName;
    }

    /**
     * Setter for RouteName.
     * @param routeName Value for String
     */
    @JsonSetter("route_name")
    public void setRouteName(String routeName) {
        this.routeName = routeName;
    }

    /**
     * Getter for Device.
     * @return Returns the String
     */
    @JsonGetter("device")
    public String getDevice() {
        return device;
    }

    /**
     * Setter for Device.
     * @param device Value for String
     */
    @JsonSetter("device")
    public void setDevice(String device) {
        this.device = device;
    }

    /**
     * Getter for RouteTo.
     * @return Returns the String
     */
    @JsonGetter("route_to")
    public String getRouteTo() {
        return routeTo;
    }

    /**
     * Setter for RouteTo.
     * @param routeTo Value for String
     */
    @JsonSetter("route_to")
    public void setRouteTo(String routeTo) {
        this.routeTo = routeTo;
    }

    /**
     * Getter for RouteDetail.
     * @return Returns the String
     */
    @JsonGetter("route_detail")
    public String getRouteDetail() {
        return routeDetail;
    }

    /**
     * Setter for RouteDetail.
     * @param routeDetail Value for String
     */
    @JsonSetter("route_detail")
    public void setRouteDetail(String routeDetail) {
        this.routeDetail = routeDetail;
    }

    /**
     * Getter for RoutePrefix.
     * @return Returns the String
     */
    @JsonGetter("route_prefix")
    public String getRoutePrefix() {
        return routePrefix;
    }

    /**
     * Setter for RoutePrefix.
     * @param routePrefix Value for String
     */
    @JsonSetter("route_prefix")
    public void setRoutePrefix(String routePrefix) {
        this.routePrefix = routePrefix;
    }

    /**
     * Converts this RouteOutgoingRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RouteOutgoingRequest [" + "routeName=" + routeName + ", device=" + device
                + ", routeTo=" + routeTo + ", routeDetail=" + routeDetail + ", routePrefix="
                + routePrefix + "]";
    }

    /**
     * Builds a new {@link RouteOutgoingRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RouteOutgoingRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(routeName, device, routeTo, routeDetail, routePrefix);
        return builder;
    }

    /**
     * Class to build instances of {@link RouteOutgoingRequest}.
     */
    public static class Builder {
        private String routeName;
        private String device;
        private String routeTo;
        private String routeDetail;
        private String routePrefix;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  routeName  String value for routeName.
         * @param  device  String value for device.
         * @param  routeTo  String value for routeTo.
         * @param  routeDetail  String value for routeDetail.
         * @param  routePrefix  String value for routePrefix.
         */
        public Builder(String routeName, String device, String routeTo, String routeDetail,
                String routePrefix) {
            this.routeName = routeName;
            this.device = device;
            this.routeTo = routeTo;
            this.routeDetail = routeDetail;
            this.routePrefix = routePrefix;
        }

        /**
         * Setter for routeName.
         * @param  routeName  String value for routeName.
         * @return Builder
         */
        public Builder routeName(String routeName) {
            this.routeName = routeName;
            return this;
        }

        /**
         * Setter for device.
         * @param  device  String value for device.
         * @return Builder
         */
        public Builder device(String device) {
            this.device = device;
            return this;
        }

        /**
         * Setter for routeTo.
         * @param  routeTo  String value for routeTo.
         * @return Builder
         */
        public Builder routeTo(String routeTo) {
            this.routeTo = routeTo;
            return this;
        }

        /**
         * Setter for routeDetail.
         * @param  routeDetail  String value for routeDetail.
         * @return Builder
         */
        public Builder routeDetail(String routeDetail) {
            this.routeDetail = routeDetail;
            return this;
        }

        /**
         * Setter for routePrefix.
         * @param  routePrefix  String value for routePrefix.
         * @return Builder
         */
        public Builder routePrefix(String routePrefix) {
            this.routePrefix = routePrefix;
            return this;
        }

        /**
         * Builds a new {@link RouteOutgoingRequest} object using the set fields.
         * @return {@link RouteOutgoingRequest}
         */
        public RouteOutgoingRequest build() {
            return new RouteOutgoingRequest(routeName, device, routeTo, routeDetail, routePrefix);
        }
    }
}
