/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for TranslationDeleteRequest type.
 */
public class TranslationDeleteRequest {
    private String transactionId;

    /**
     * Default constructor.
     */
    public TranslationDeleteRequest() {
    }

    /**
     * Initialization constructor.
     * @param  transactionId  String value for transactionId.
     */
    public TranslationDeleteRequest(
            String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * Getter for TransactionId.
     * @return Returns the String
     */
    @JsonGetter("transaction_id")
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Setter for TransactionId.
     * @param transactionId Value for String
     */
    @JsonSetter("transaction_id")
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * Converts this TranslationDeleteRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TranslationDeleteRequest [" + "transactionId=" + transactionId + "]";
    }

    /**
     * Builds a new {@link TranslationDeleteRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TranslationDeleteRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(transactionId);
        return builder;
    }

    /**
     * Class to build instances of {@link TranslationDeleteRequest}.
     */
    public static class Builder {
        private String transactionId;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  transactionId  String value for transactionId.
         */
        public Builder(String transactionId) {
            this.transactionId = transactionId;
        }

        /**
         * Setter for transactionId.
         * @param  transactionId  String value for transactionId.
         * @return Builder
         */
        public Builder transactionId(String transactionId) {
            this.transactionId = transactionId;
            return this;
        }

        /**
         * Builds a new {@link TranslationDeleteRequest} object using the set fields.
         * @return {@link TranslationDeleteRequest}
         */
        public TranslationDeleteRequest build() {
            return new TranslationDeleteRequest(transactionId);
        }
    }
}
