/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for TranslationSetupRequest type.
 */
public class TranslationSetupRequest {
    private String fromNumber;
    private String callerDidgateway;
    private String calledDidgateway;
    private String destinationNumber;
    private String externalId;

    /**
     * Default constructor.
     */
    public TranslationSetupRequest() {
    }

    /**
     * Initialization constructor.
     * @param  fromNumber  String value for fromNumber.
     * @param  callerDidgateway  String value for callerDidgateway.
     * @param  calledDidgateway  String value for calledDidgateway.
     * @param  destinationNumber  String value for destinationNumber.
     * @param  externalId  String value for externalId.
     */
    public TranslationSetupRequest(
            String fromNumber,
            String callerDidgateway,
            String calledDidgateway,
            String destinationNumber,
            String externalId) {
        this.fromNumber = fromNumber;
        this.callerDidgateway = callerDidgateway;
        this.calledDidgateway = calledDidgateway;
        this.destinationNumber = destinationNumber;
        this.externalId = externalId;
    }

    /**
     * Getter for FromNumber.
     * @return Returns the String
     */
    @JsonGetter("from_number")
    public String getFromNumber() {
        return fromNumber;
    }

    /**
     * Setter for FromNumber.
     * @param fromNumber Value for String
     */
    @JsonSetter("from_number")
    public void setFromNumber(String fromNumber) {
        this.fromNumber = fromNumber;
    }

    /**
     * Getter for CallerDidgateway.
     * @return Returns the String
     */
    @JsonGetter("caller_didgateway")
    public String getCallerDidgateway() {
        return callerDidgateway;
    }

    /**
     * Setter for CallerDidgateway.
     * @param callerDidgateway Value for String
     */
    @JsonSetter("caller_didgateway")
    public void setCallerDidgateway(String callerDidgateway) {
        this.callerDidgateway = callerDidgateway;
    }

    /**
     * Getter for CalledDidgateway.
     * @return Returns the String
     */
    @JsonGetter("called_didgateway")
    public String getCalledDidgateway() {
        return calledDidgateway;
    }

    /**
     * Setter for CalledDidgateway.
     * @param calledDidgateway Value for String
     */
    @JsonSetter("called_didgateway")
    public void setCalledDidgateway(String calledDidgateway) {
        this.calledDidgateway = calledDidgateway;
    }

    /**
     * Getter for DestinationNumber.
     * @return Returns the String
     */
    @JsonGetter("destination_number")
    public String getDestinationNumber() {
        return destinationNumber;
    }

    /**
     * Setter for DestinationNumber.
     * @param destinationNumber Value for String
     */
    @JsonSetter("destination_number")
    public void setDestinationNumber(String destinationNumber) {
        this.destinationNumber = destinationNumber;
    }

    /**
     * Getter for ExternalId.
     * @return Returns the String
     */
    @JsonGetter("external_id")
    public String getExternalId() {
        return externalId;
    }

    /**
     * Setter for ExternalId.
     * @param externalId Value for String
     */
    @JsonSetter("external_id")
    public void setExternalId(String externalId) {
        this.externalId = externalId;
    }

    /**
     * Converts this TranslationSetupRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TranslationSetupRequest [" + "fromNumber=" + fromNumber + ", callerDidgateway="
                + callerDidgateway + ", calledDidgateway=" + calledDidgateway
                + ", destinationNumber=" + destinationNumber + ", externalId=" + externalId + "]";
    }

    /**
     * Builds a new {@link TranslationSetupRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TranslationSetupRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(fromNumber, callerDidgateway, calledDidgateway,
                destinationNumber, externalId);
        return builder;
    }

    /**
     * Class to build instances of {@link TranslationSetupRequest}.
     */
    public static class Builder {
        private String fromNumber;
        private String callerDidgateway;
        private String calledDidgateway;
        private String destinationNumber;
        private String externalId;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  fromNumber  String value for fromNumber.
         * @param  callerDidgateway  String value for callerDidgateway.
         * @param  calledDidgateway  String value for calledDidgateway.
         * @param  destinationNumber  String value for destinationNumber.
         * @param  externalId  String value for externalId.
         */
        public Builder(String fromNumber, String callerDidgateway, String calledDidgateway,
                String destinationNumber, String externalId) {
            this.fromNumber = fromNumber;
            this.callerDidgateway = callerDidgateway;
            this.calledDidgateway = calledDidgateway;
            this.destinationNumber = destinationNumber;
            this.externalId = externalId;
        }

        /**
         * Setter for fromNumber.
         * @param  fromNumber  String value for fromNumber.
         * @return Builder
         */
        public Builder fromNumber(String fromNumber) {
            this.fromNumber = fromNumber;
            return this;
        }

        /**
         * Setter for callerDidgateway.
         * @param  callerDidgateway  String value for callerDidgateway.
         * @return Builder
         */
        public Builder callerDidgateway(String callerDidgateway) {
            this.callerDidgateway = callerDidgateway;
            return this;
        }

        /**
         * Setter for calledDidgateway.
         * @param  calledDidgateway  String value for calledDidgateway.
         * @return Builder
         */
        public Builder calledDidgateway(String calledDidgateway) {
            this.calledDidgateway = calledDidgateway;
            return this;
        }

        /**
         * Setter for destinationNumber.
         * @param  destinationNumber  String value for destinationNumber.
         * @return Builder
         */
        public Builder destinationNumber(String destinationNumber) {
            this.destinationNumber = destinationNumber;
            return this;
        }

        /**
         * Setter for externalId.
         * @param  externalId  String value for externalId.
         * @return Builder
         */
        public Builder externalId(String externalId) {
            this.externalId = externalId;
            return this;
        }

        /**
         * Builds a new {@link TranslationSetupRequest} object using the set fields.
         * @return {@link TranslationSetupRequest}
         */
        public TranslationSetupRequest build() {
            return new TranslationSetupRequest(fromNumber, callerDidgateway, calledDidgateway,
                    destinationNumber, externalId);
        }
    }
}
