/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example;

import io.apimatic.core.authentication.HeaderAuth;
import java.util.Collections;

/**
 * Utility class for authorization and token management.
 */
public class BasicAuthManager extends HeaderAuth implements BasicAuthCredentials {

    private String username;

    private String password;

    /**
     * Constructor.
     * @param username String value for username.
     * @param password String value for password.
     */
    public BasicAuthManager(String username, String password) {
        super(Collections.singletonMap("Authorization",
                ApiHelper.getBase64EncodedCredentials(username, password)));
        this.username = username;
        this.password = password;
    }

    /**
     * String value for username.
     * @return username
     */
    public String getUsername() {
        return username;
    }

    /**
     * String value for password.
     * @return password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Checks if provided credentials matched with existing ones.
     * @param username String value for credentials.
     * @param password String value for credentials.
     * @return true if credentials matched.
     */
    public boolean equals(String username, String password) {
        return username.equals(getUsername())
                && password.equals(getPassword());
    }

    /**
     * Converts this BasicAuthManager into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BasicAuthManager [" + "username=" + username + ", password=" + password + "]";
    }

}
