/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example;

import com.example.controllers.AgentController;
import com.example.controllers.CallController;
import com.example.controllers.ConversationAIController;
import com.example.controllers.DIDController;
import com.example.controllers.DeviceController;
import com.example.controllers.IVRController;
import com.example.controllers.MaskingController;
import com.example.controllers.QueueController;
import com.example.controllers.RouteController;
import com.example.controllers.TranslationController;
import com.example.http.client.HttpCallback;
import com.example.http.client.HttpClientConfiguration;
import com.example.http.client.ReadonlyHttpClientConfiguration;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.authentication.Authentication;
import io.apimatic.coreinterfaces.compatibility.CompatibilityFactory;
import io.apimatic.coreinterfaces.http.HttpClient;
import io.apimatic.okhttpclient.adapter.OkClient;
import java.util.AbstractMap.SimpleEntry;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Consumer;

/**
 * Gateway class for the library.
 * This class acts as a factory for Controllers.
 * It holds the state of the SDK.
 */
public final class SiskomVoiceAPIClient implements Configuration {

    /**
     * Private store for controllers.
     */
    private CallController call;
    private MaskingController masking;
    private TranslationController translation;
    private DeviceController device;
    private AgentController agent;
    private QueueController queue;
    private RouteController route;
    private IVRController iVR;
    private ConversationAIController conversationAI;
    private DIDController dID;

    private static final CompatibilityFactory compatibilityFactory = new CompatibilityFactoryImpl();

    private static String userAgent = "APIMATIC 3.0";

    /**
     * Current API environment.
     */
    private final Environment environment;

    /**
     * The HTTP Client instance to use for making HTTP requests.
     */
    private final HttpClient httpClient;

    /**
     * Http Client Configuration instance.
     */
    private final ReadonlyHttpClientConfiguration httpClientConfig;

    /**
     * BasicAuthManager.
     */
    private BasicAuthManager basicAuthManager;

    /**
     * Map of authentication Managers.
     */
    private Map<String, Authentication> authentications;


    /**
     * Callback to be called before and after the HTTP call for an endpoint is made.
     */
    private final HttpCallback httpCallback;

    private SiskomVoiceAPIClient(Environment environment, HttpClient httpClient,
            ReadonlyHttpClientConfiguration httpClientConfig, String username, String password,
            Map<String, Authentication> authentications, HttpCallback httpCallback) {
        this.environment = environment;
        this.httpClient = httpClient;
        this.httpClientConfig = httpClientConfig;
        this.httpCallback = httpCallback;
        this.authentications = 
                (authentications == null) ? new HashMap<>() : new HashMap<>(authentications);
        if (this.authentications.containsKey("global")) {
            this.basicAuthManager = (BasicAuthManager) this.authentications.get("global");
        }

        if (!this.authentications.containsKey("global")
                || !getBasicAuthCredentials().equals(username, password)) {
            this.basicAuthManager = new BasicAuthManager(username, password);
            this.authentications.put("global", basicAuthManager);
        }

        GlobalConfiguration globalConfig = new GlobalConfiguration.Builder()
                .authentication(this.authentications).compatibilityFactory(compatibilityFactory)
                .httpClient(httpClient).baseUri(server -> getBaseUri(server))
                .callback(httpCallback)
                .userAgent(userAgent)
                .build();
        call = new CallController(globalConfig);
        masking = new MaskingController(globalConfig);
        translation = new TranslationController(globalConfig);
        device = new DeviceController(globalConfig);
        agent = new AgentController(globalConfig);
        queue = new QueueController(globalConfig);
        route = new RouteController(globalConfig);
        iVR = new IVRController(globalConfig);
        conversationAI = new ConversationAIController(globalConfig);
        dID = new DIDController(globalConfig);
    }

    /**
     * Shutdown the underlying HttpClient instance.
     */
    public static void shutdown() {
        OkClient.shutdown();
    }

    /**
     * Get the instance of CallController.
     * @return call
     */
    public CallController getCallController() {
        return call;
    }

    /**
     * Get the instance of MaskingController.
     * @return masking
     */
    public MaskingController getMaskingController() {
        return masking;
    }

    /**
     * Get the instance of TranslationController.
     * @return translation
     */
    public TranslationController getTranslationController() {
        return translation;
    }

    /**
     * Get the instance of DeviceController.
     * @return device
     */
    public DeviceController getDeviceController() {
        return device;
    }

    /**
     * Get the instance of AgentController.
     * @return agent
     */
    public AgentController getAgentController() {
        return agent;
    }

    /**
     * Get the instance of QueueController.
     * @return queue
     */
    public QueueController getQueueController() {
        return queue;
    }

    /**
     * Get the instance of RouteController.
     * @return route
     */
    public RouteController getRouteController() {
        return route;
    }

    /**
     * Get the instance of IVRController.
     * @return iVR
     */
    public IVRController getIVRController() {
        return iVR;
    }

    /**
     * Get the instance of ConversationAIController.
     * @return conversationAI
     */
    public ConversationAIController getConversationAIController() {
        return conversationAI;
    }

    /**
     * Get the instance of DIDController.
     * @return dID
     */
    public DIDController getDIDController() {
        return dID;
    }

    /**
     * Current API environment.
     * @return environment
     */
    public Environment getEnvironment() {
        return environment;
    }

    /**
     * The HTTP Client instance to use for making HTTP requests.
     * @return httpClient
     */
    private HttpClient getHttpClient() {
        return httpClient;
    }

    /**
     * Http Client Configuration instance.
     * @return httpClientConfig
     */
    public ReadonlyHttpClientConfiguration getHttpClientConfig() {
        return httpClientConfig;
    }

    /**
     * The credentials to use with BasicAuth.
     * @return basicAuthCredentials
     */
    public BasicAuthCredentials getBasicAuthCredentials() {
        return basicAuthManager;
    }
    /**
     * The timeout to use for making HTTP requests.
     * @deprecated This method will be removed in a future version. Use
     *             {@link #getHttpClientConfig()} instead.
     *
     * @return timeout
     */
    @Deprecated
    public long timeout() {
        return httpClientConfig.getTimeout();
    }

    /**
     * Get base URI by current environment.
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(Server server) {
        Map<String, SimpleEntry<Object, Boolean>> parameters = new HashMap<>();
        StringBuilder baseUrl = new StringBuilder(environmentMapper(environment, server));
        ApiHelper.appendUrlWithTemplateParameters(baseUrl, parameters);
        return baseUrl.toString();
    }

    /**
     * Get base URI by current environment.
     * @return Processed base URI
     */
    public String getBaseUri() {
        return getBaseUri(Server.SERVER_1);
    }


    /**
     * Get base URI by current environment.
     * 
     * @param server string for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(String server) {
        return getBaseUri(Server.fromString(server));
    }


    /**
     * Base URLs by environment and server aliases.
     * @param environment Environment for which to get the base URI
     * @param server Server for which to get the base URI
     * @return base URL
     */
    private static String environmentMapper(Environment environment, Server server) {
        if (environment.equals(Environment.PRODUCTION)) {
            if (server.equals(Server.SERVER_1)) {
                return "api.siskom.cloud";
            }
        }
        return "api.siskom.cloud";
    }

    /**
     * Converts this SiskomVoiceAPIClient into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SiskomVoiceAPIClient [" + "environment=" + environment + ", httpClientConfig="
                + httpClientConfig + ", authentications=" + authentications + "]";
    }

    /**
     * Builds a new {@link SiskomVoiceAPIClient.Builder} object.
     * Creates the instance with the state of the current client.
     * @return a new {@link SiskomVoiceAPIClient.Builder} object
     */
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.environment = getEnvironment();
        builder.httpClient = getHttpClient();
        builder.username = getBasicAuthCredentials().getUsername();
        builder.password = getBasicAuthCredentials().getPassword();
        builder.authentications = authentications;
        builder.httpCallback = httpCallback;
        builder.httpClientConfig(configBldr -> configBldr =
                ((HttpClientConfiguration) httpClientConfig).newBuilder());
        return builder;
    }

    /**
     * Class to build instances of {@link SiskomVoiceAPIClient}.
     */
    public static class Builder {

        private Environment environment = Environment.PRODUCTION;
        private HttpClient httpClient;
        private String username = "TODO: Replace";
        private String password = "TODO: Replace";
        private Map<String, Authentication> authentications = null;
        private HttpCallback httpCallback = null;
        private HttpClientConfiguration.Builder httpClientConfigBuilder =
                new HttpClientConfiguration.Builder();


        /**
         * Credentials setter for BasicAuth.
         * @param username String value for username.
         * @param password String value for password.
         * @return Builder
         */
        public Builder basicAuthCredentials(String username, String password) {
            if (username == null) {
                throw new NullPointerException("Username cannot be null.");
            }
            if (password == null) {
                throw new NullPointerException("Password cannot be null.");
            }
            this.username = username;
            this.password = password;
            return this;
        }

        /**
         * Current API environment.
         * @param environment The environment for client.
         * @return Builder
         */
        public Builder environment(Environment environment) {
            this.environment = environment;
            return this;
        }

        /**
         * The timeout to use for making HTTP requests.
         * @deprecated This method will be removed in a future version. Use
         *             {@link #httpClientConfig(Consumer) httpClientConfig} instead.
         * @param timeout must be greater then 0.
         * @return Builder
         */
        @Deprecated
        public Builder timeout(long timeout) {
            this.httpClientConfigBuilder.timeout(timeout);
            return this;
        }

        /**
         * HttpCallback.
         * @param httpCallback Callback to be called before and after the HTTP call.
         * @return Builder
         */
        public Builder httpCallback(HttpCallback httpCallback) {
            this.httpCallback = httpCallback;
            return this;
        }

        /**
         * Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param action Consumer for the builder of httpClientConfiguration.
         * @return Builder
         */
        public Builder httpClientConfig(Consumer<HttpClientConfiguration.Builder> action) {
            action.accept(httpClientConfigBuilder);
            return this;
        }

        /**
         * Builds a new SiskomVoiceAPIClient object using the set fields.
         * @return SiskomVoiceAPIClient
         */
        public SiskomVoiceAPIClient build() {
            HttpClientConfiguration httpClientConfig = httpClientConfigBuilder.build();
            httpClient = new OkClient(httpClientConfig.getConfiguration(), compatibilityFactory);

            return new SiskomVoiceAPIClient(environment, httpClient, httpClientConfig, username,
                    password, authentications, httpCallback);
        }
    }
}