/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.controllers;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import com.example.ApiHelper;
import com.example.SiskomVoiceAPIClient;
import com.example.exceptions.ApiException;
import com.example.models.Blast;
import com.example.models.Blastrequest;
import io.apimatic.core.testing.TestHelper;
import java.util.LinkedHashMap;
import java.util.Map;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

public class CallControllerTest extends BaseControllerTest {

    /**
     * Client instance.
     */
    private static SiskomVoiceAPIClient client;
    
    /**
     * Controller instance (for all tests).
     */
    private static CallController controller;

    /**
     * Setup test class.
     */
    @BeforeClass
    public static void setUpClass() {
        client = createConfiguration();
        controller = client.getCallController();
    }

    /**
     * Tear down test class.
     */
    @AfterClass
    public static void tearDownClass() {
        controller = null;
    }

    /**
     * SUPPORTED **LANGUAGE** : \* id-ID \* en-US **GENDER** : \* MALE \* FEMALE.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testBlast() throws Exception {
        // Parameters for the API call
        Blastrequest body = ApiHelper.deserialize(
                "{\r\n  \"callerid\": \"6285757920463\",\r\n  \"destination\": \"6285772337980\",\r"
                + "\n  \"text_to_speech\": \"Halo mas machri apa kabar? halo mas machri apa\",\r\n "
                + " \"language\": \"id_ID\",\r\n  \"gender\": \"FEMALE\",\r\n  \"repeat\": 10,\r\n "
                + " \"external_id\": \"[EXTERNAL_ID]\",\r\n  \"callback_url\": \"https://eov2zjk1xw"
                + "qtjan.m.pipedream.net\"\r\n}",
                Blastrequest.class);

        // Set callback and perform API call
        Blast result = null;
        try {
            result = controller.blast(body);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test headers
        Map<String, String> headers = new LinkedHashMap<String, String>();
        headers.put("Content-Type", TestHelper.nullString);
        headers.put("Date", TestHelper.nullString);
        headers.put("Server", TestHelper.nullString);
        headers.put("X-Powered-By", TestHelper.nullString);
        headers.put("Content-Length", TestHelper.nullString);
        headers.put("ETag", TestHelper.nullString);
        headers.put("Keep-Alive", TestHelper.nullString);
        headers.put("Connection", TestHelper.nullString);
        
        assertTrue("Headers do not match", TestHelper.areHeadersProperSubsetOf(
                headers, httpResponse.getResponse().getHeaders().asSimpleMap(), true));

        // Test whether the captured response is as we expected
        assertNotNull("Result does not exist", 
                result);
        assertTrue("Response body does not match in keys", 
                TestHelper.isJsonObjectProperSubsetOf(
                "{\r\n  \"response\": true,\r\n  \"rcode\": {\r\n    \"transaction_id\": \"489EF417"
                + "5D9E35DDAEFD74839DB9558D\",\r\n    \"callback_key\": \"25c1e6ec24db6cf8bcff66576"
                + "1e1c985\",\r\n    \"destination\": \"62127867676\",\r\n    \"text_to_speech\": "
                + "\"Hai.... Selamat datang saudara-saudaraku, anda adalah pelanggan utama hari ini"
                + ", selamat yaaa gaeees!\",\r\n    \"language\": \"id-ID\",\r\n    \"gender\": \"F"
                + "EMALE\",\r\n    \"VoiceRepeat\": \"2\",\r\n    \"external_id\": \"93894893483984"
                + "938\",\r\n    \"callback_url\": \"http\"\r\n  }\r\n}",
                TestHelper.convertStreamToString(httpResponse.getResponse().getRawBody()), 
                false, true, false));
    }

}
